### ISSUE TITLE
Add the possibility to show opfab menu to only a set of groups

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#1257]
As for business menu , you can choose to show menu depending of user group membership , do the same for native opfab menu and submenu ( Feed , Archives ......  ) 

The configuration has to be set in ui-menu.json . 

Remove navbar.hidden in web-ui.json 

Possible configuration : 
{
  "coreMenusVisibility":
  [
    {
      "id": "feed",
      "visible": true,
      "showOnlyForGroups": ["ReadOnly","Planner"]
    }
    
  ],

  "menus": [
    {
      "id": "menu1",
      "label": "title.single",
      "entries": [ ......... 

 

visible set to false or true by default ?? → to discuss

i would propose false so when we introduce a new menu , the opfab user shall not see it if does not touch his config (this way we can for example introduce new menu for beta features with no impact an exitisting installation)

 

Modify default config to use this option and add cypress test

**Comment by AlexGuironnetRTE** [comment]
After discussion:

- If a core menu is not present in coreMenusVisibility, it’s not visible.
- If a core menu doesn’t have a visible property, or it is set to null or false, it’s not visible.
- If a core menu has its visible property set to true or in the case of custom menus:
  - If showOnlyForGroups is not present, null or an empty array : menu is visible for everyone
  - If showOnlyForGroups is present and with a non-empty array as a value: menu is visible only for users from listed groups.
