### ISSUE TITLE
Add configuration to exclude some states from the notification configuration screen

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#1263]
Add a parameter in state in config.json  named : isOnlyAChildState with a boolean value 

if true it means this state is only used for child cards and shall not be seen on : 
- feed notification screen
- in archives filters 

default value is false 

- [ ] Set in the examples (config.json)  the value when needed
- [ ] Modify the cypress test for archives to check child states are not present 
- [ ] Add a cypress test for feed , this will intiate a first feedconfiguration screen cypress test 
- [ ] Add documentation in chapter https://opfab.github.io/documentation/current/reference_doc/#_configure_the_response_in_config_json

**Comment by AlexGuironnetRTE** [comment]
The issue description is clear to me. Maybe we can add "update state object in swagger template" to the task list?

I'm not too happy with the naming of the property though. To me:
- Adding "state" at the end is not necessary as it is a property of the state object
- With no prior knowledge, I would have thought that "aChildState" means that it is the state itself that is a child (of another state).

`isChildCardSpecific` maybe ? 

Or, if there is a chance that in the future we might want to exclude from the archive filters and feed notification screens some states that are not used only in child cards, maybe we should focus on that when naming the property: `isHidden`, `isNotForDisplay` or something along those lines. What do you think ?
