### ISSUE TITLE
Gradle/Travis cache issue

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#1279]
The travis build is not doing a “clean” build, and it is using the --build-cache option.

It’s probably better for build duration, but as we saw with OC-1779, it can cause us to discover build failures after the fact.

Here it was an update on the swagger generation dependency that suddenly caused the builds to fail a few hours after it was introduced, even though the builds for the branch and the PR introducing it both passed.

This was because in the branch and PR build introducing the version update, the build didn’t really use the new version of the swagger generator to generate the classes, it just took task output from cache : 
> Task :client:cards-client-data:generateAvroProtocol NO-SOURCE
> Task :client:cards-client-data:generateAvroJava FROM-CACHE
> Task :client:cards-client-data:resolveSwaggerTemplate NO-SOURCE
> Task :client:cards-client-data:generateSwaggerCodeModel FROM-CACHE
> Task :client:cards-client-data:generateSwaggerCode NO-SOURCE
> Task :client:cards-client-data:compileJava FROM-CACHE
> Task :client:cards-client-data:processResources NO-SOURCE
> Task :client:cards-client-data:classes UP-TO-DATE
> Task :client:cards-client-data:jar

 

Maybe the fact that gradle doesn’t “understand” that a version update on swagger impacts those tasks is due to our complex build, so ideally we should fix that.

If that’s not doable, we could try disabling the cache and see how much longer the build gets.

**Comment by quinarygio** [comment]
I confirm that gradle seem not to detect a library upgrade on a task and resuse the cache.
Disabling --build-cache option seems to not cause a big change in build time.
