### ISSUE TITLE
Documentation - Some links are not working anymore

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#1283]
This is probably due to the new version of the Asciidoctor Gradle plugin (change in the include directive or gradle-rootdir behaviour).

Check normal docs, single-page docs (both inside links and cross documents) + images.
Fix warnings: 

> Jul 30, 2021 11:01:23 AM uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb content
> INFO: possible invalid reference: Cards-publication service
> Jul 30, 2021 11:01:23 AM uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb content
> INFO: possible invalid reference: card_structure
> Jul 30, 2021 11:01:23 AM uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/document.rb content
> INFO: possible invalid reference: response_cards
> Jul 30, 2021 11:01:25 AM uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/converter/html5.rb convert_document
> INFO: possible invalid reference: card_recipients
> Jul 30, 2021 11:01:26 AM uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/converter/html5.rb convert_document
> INFO: possible invalid reference: /home/guironnetale/Projects/opfab/operatorfabric-core/documentation/current/CICD/index.adoc
> 
>

**Comment by AlexGuironnetRTE** [comment]
See message: https://github.com/spring-projects/spring-boot/issues/26136#issuecomment-820562345

**Comment by AlexGuironnetRTE** [comment]
Most of the broken links have already been taken care of by https://github.com/opfab/operatorfabric-core/commit/7ade57a8d40b4c12f9ad8d11b0bb2ad0ab35842d
