### ISSUE TITLE
Gradle - take advantage of the Spring boot dependency management plugin

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#1284]
We’re using the dependency management plugin for spring yet overriding the versions with a shared variable to make sure that different packages stay in sync, which is the point of the dependency management plugin.

See https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/htmlsingle/#managing-dependencies

Basically since we register the dependency management plugin, we should define dependencies without stating their version as explained here.
We should only override the versions if we really need it as there would then be no guarantee of compatibility.

**Comment by AlexGuironnetRTE** [comment]
Closed by #1481
