### ISSUE TITLE
Manage ui version from VERSION file (using Gradle?)

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#1290]
A version is defined for the OperatorFabric UI in the package.json file

   "name": "operatorfabric-ui-main","version": "0.0.1",

This version should be automatically updated to match the global OpFab version set in the VERSION file.

**Comment by AlexGuironnetRTE** [comment]
Now that they're both managed by the `prepare_release_version.sh` script (OC-1558) I don't think it's worth the trouble to link the two versions.
