### ISSUE TITLE
Cypress gets reinstalled for every CI build

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#1312]
Move cypress installation to install stage

**Comment by AlexGuironnetRTE** [comment]
Moving it to the install stage is actually not optimal as it would get installed even for stages that don't need it. Instead, caching its node_modules directory should allow the npmInstall task to be found up-to-date by Gradle.

Note: From local behaviour, it seems that npmInstall is already taking into account the right inputs & outputs in deciding whether is up to date, no additional configuration (see #1413) is needed. To be tested.
