### ISSUE TITLE
Migrating to Gradle v7

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#1335]
Mostly :

- Replacing deprecated configurations (compile & testCompile) 
- Fix "Implicit duplicate strategy for Copy or archive tasks has been deprecated"
- Fix Asciidoctor plugin deprecation warning

**Comment by AlexGuironnetRTE** [comment]
Build scan from 6.9 build for reference: https://scans.gradle.com/s/c2q5wbtpwl524

**Comment by AlexGuironnetRTE** [comment]
On the difference between implementation & api configurations:

- https://docs.gradle.org/current/userguide/building_java_projects.html#sec:building_java_libraries
- https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_recognizing_dependencies

**Comment by AlexGuironnetRTE** [comment]
About "Implicit duplicate strategy for Copy or archive tasks has been deprecated":
https://github.com/gradle/gradle/issues/17236

**Comment by AlexGuironnetRTE** [comment]
Build scan in v7: https://scans.gradle.com/s/ct2thtkuxmx3a
