### ISSUE TITLE
Remove duplicate Enum classes

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#1336]
In the java code, several Enum classes are duplicated, for example:

-services/users/build/swagger/src/main/java/org/lfenergy/operatorfabric/users/model/RightsEnum.java
-client/users/src/main/java/org/opfab/client/users/model/RightsEnum.java

In this example, the first one is generated and the second one is a normal class, with the following comment: This enum is created by hand because Swagger can't handle enums. It should match the corresponding enum definition in the Users API.

Apparently swagger does handle enums now so in this case it would be better to have it generated in the client library and avoid duplications by always using this class? 

Look for the other duplicated enums and fix them as well.

**Comment by evgenyrakitov** [comment]
I can take on this task

**Comment by AlexGuironnetRTE** [comment]
Awesome thanks! Let us know if you need any help!

**Comment by freddidierRTE** [comment]
too old issue
