### ISSUE TITLE
Remove unused dependency reporting plugins from gradle 

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#1359]
it is not used by the project

**Comment by AlexGuironnetRTE** [comment]
From the licences point of view, LFX Security now provides us with a report that is regularly updated:

https://security.lfx.linuxfoundation.org/#/89163060-0071-496b-80c7-899fb9caffb1/licenses

This makes plugin `com.github.jk1.dependency-license-report` unnecessary.

**Comment by AlexGuironnetRTE** [comment]
Regarding security vulnerabilities, we now rely on [LFX Security](https://security.lfx.linuxfoundation.org/#/89163060-0071-496b-80c7-899fb9caffb1/issues) for recurrent scans as well the Whitesource Bot for checks on PRs.

This makes plugin `org.owasp.dependencycheck` unnecessary.
