### ISSUE TITLE
Fix "compile dateFormat now (using en locale fallback)" test (failing at night on CI)

### ISSUE THREAD

**Issue by AlexGuironnetRTE** [opfab/operatorfabric-core#1427]
This UI test fails when run on the CI at night

Error message:

> FAILED TESTS:
> Handlebars Services
>     #executeTemplate
>       ✖ compile dateFormat now (using en locale fallback)
> 
>         Chrome Headless 91.0.4472.114 (Linux x86_64)
>       Error: Expected 'July 9th 2021' to equal 'July 8th 2021'.
>           at <Jasmine>
>           at src/app/modules/cards/services/handlebars.service.spec.ts:513:36
>           at Object.next (node_modules/rxjs/dist/esm5/internal/Subscriber.js:122:1)
>           at SafeSubscriber.Subscriber._next (node_modules/rxjs/dist/esm5/internal/Subscriber.js:62:1)

Example of builds when it happened:

- https://app.travis-ci.com/github/opfab/operatorfabric-core/builds/232234419 (launched around 1:50 am CET)
- https://app.travis-ci.com/github/opfab/operatorfabric-core/builds/232228367 (launched around 0:20 am CET)

Given the timeframe it's mostly an issue for RenovateBot PRs (which means we have to launch them again in the morning, so that defeats the purpose of having it run only at night). In the future it might be an issue for contributors working in a different timezone though.

**Comment by freddidierRTE** [comment]
we can change the test by replacing now by a fix date as the aim is to test formatting

**Comment by freddidierRTE** [comment]
Proposal : 

Separate in two test : 
- one for testing the use of now (in epoch date)
- one to testing date formatting using a fix date value
