### ISSUE TITLE
New CSS class --> class:'text-warning'  (Compatible with Night/Day Mode)

### ISSUE THREAD

**Issue by bengoutaeli** [opfab/operatorfabric-core#1445]
@freddidierRTE 
We would like to have a new color css class like "text-danger" or "text-sucess" but with the warning texts, in orange.
E.g : 
![image](https://user-images.githubusercontent.com/78432948/125464872-1c1136b8-2afc-4282-8922-d9057d987188.png)

**Comment by freddidierRTE** [comment]
i would propose three color :
opfab-text-danger = red 
opfab-text-warning = orange
opfab-text-sucess = green

??

**Comment by bengoutaeli** [comment]
It's ok for me

**Comment by freddidierRTE** [comment]
+ add documentation in https://opfab.github.io/documentation/current/reference_doc/#opfab_template_style
