### ISSUE TITLE
Saturday Night Tests

### ISSUE THREAD

**Issue by AlexGuironnetRTE** [opfab/operatorfabric-core#1457]
As discussed during our daily meeting today, it would be good to routinely test OpFab with an older version of MongoDB to make sure it's still compatible and we're not introducing queries that would require existing deployments to switch to a newer MongoDB version.

- Are there other similar things that we would like to test?
- When should these tests run: we were thinking of adding them to the CICD to be run every Saturday night for example, this way as we do our releases on Mondays usually we would have the test result by then.

**Comment by freddidierRTE** [comment]
Done
