### ISSUE TITLE
Generate Avro task gives warning about ignored property

### ISSUE THREAD

**Issue by AlexGuironnetRTE** [opfab/operatorfabric-core#1532]
The build gives the following warning: 

> > Task :client:cards-client-data:generateAvroJava
> Ignored the org.opfab.avro.Card.publishDate.logicalType property ("timestamp-millis"). It should probably be nested inside the "type" for the field.
> Ignored the org.opfab.avro.Card.lttd.logicalType property ("timestamp-millis"). It should probably be nested inside the "type" for the field.
> Ignored the org.opfab.avro.Card.startDate.logicalType property ("timestamp-millis"). It should probably be nested inside the "type" for the field.
> Ignored the org.opfab.avro.Card.endDate.logicalType property ("timestamp-millis"). It should probably be nested inside the "type" for the field.
> Ignored the org.opfab.avro.Timespan.start.logicalType property ("timestamp-millis"). It should probably be nested inside the "type" for the field.
> Ignored the org.opfab.avro.Timespan.end.logicalType property ("timestamp-millis"). It should probably be nested inside the "type" for the field.
> Ignored the org.opfab.avro.Card.publishDate.logicalType property ("timestamp-millis"). It should probably be nested inside the "type" for the field.
> Ignored the org.opfab.avro.Card.lttd.logicalType property ("timestamp-millis"). It should probably be nested inside the "type" for the field.
> Ignored the org.opfab.avro.Card.startDate.logicalType property ("timestamp-millis"). It should probably be nested inside the "type" for the field.
> Ignored the org.opfab.avro.Card.endDate.logicalType property ("timestamp-millis"). It should probably be nested inside the "type" for the field.

Is that a problem?

**Comment by JeroenGommans** [comment]
It is not nice. I fixed it and also made sure you can now send a startDate with a Java Instant as parameter (previously you needed to convert to a Long).
