### ISSUE TITLE
Handle duplicate warning properly in Gradle build

### ISSUE THREAD

**Issue by AlexGuironnetRTE** [opfab/operatorfabric-core#1543]
When migrating to Gradle v7, the following warning became an error:

> Execution failed for task ':services:core:businessconfig-business-service:processResources'.
> > Entry application.yml is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.1.1/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.

(same thing happens for the other services of course).

See https://github.com/opfab/operatorfabric-core/issues/1335#issuecomment-887294188 for details.

To move the Gradle v7 upgrade along and because I suspect the guilty plugin will be easier to track once we have reorganized the gradle build, I went with [the fix described here](https://discuss.gradle.org/t/gradle-7-fail-for-duplicates-in-copy-specs-has-no-duplicates-in-project/39834/9) (basically saying duplicates are ok again) and logged this issue to handle this correctly.

UPDATE: This will also need to be addressed for the sourcesJar task (see #1561).

**Comment by AlexGuironnetRTE** [comment]
Interesting links: 
https://github.com/gradle/gradle/issues/17236
https://github.com/gradle/gradle/issues/13578

**Comment by freddidierRTE** [comment]
@AlexGuironnetRTE  : check if still a problem

**Comment by quinarygio** [comment]
Issue is still present

**Comment by freddidierRTE** [comment]
Issue not present anymore
