### ISSUE TITLE
Allow different drivers to be provided for external devices

### ISSUE THREAD

**Issue by AlexGuironnetRTE** [opfab/operatorfabric-core#1654]
Define the interface that drivers need to implement
How can the code for these drivers be provided? Will dependency injection work if they are provided in a mounted directory for docker containers?
Otherwise client projects would need to rebuild the docker images for the external-devices service...

If we can't do something like spring (picks up whatever fitting driver is available at run-time), we can pass the driver to use as a configuration property.

Can we have several drivers at the same time? Maybe easier to do with configuration property?

Add a device type to the device configuration object

The ExternalDeviceDriver interface and the associated factory, as well as the custom exceptions, need to be made available as jars for people to implement them with other protocols. I tried just moving them to the external devices client module along with 
the generated model classes (and including it as a dependency in the external devices service, but that causes a conflict with the interfaces of the same name generated in the service module.

For example this works fine:
```
Device myMethod()  {
    return new DeviceData(a,b,c);
}
```
because here Device is the interface generated at the service level, that DeviceData implements

But if we bring external-devices-client-data as a dependency, the Device interface gets overriden with the Device class of the same name, and we get messages such as:
```
/operatorfabric-core/services/external-devices/src/main/java/org/opfab/externaldevices/services/DevicesService.java:162: error: incompatible types: DeviceData cannot be converted to Device
                .build();
```

So these should probably be in a separate jar (naming ?). In any case, that makes sense also from a usage point of view as people wanting to call the external devices API (who will need the client data model classes) might not need the interfaces to create a new driver, and vice-versa.

**Comment by AlexGuironnetRTE** [comment]
https://www.baeldung.com/java-spi

**Comment by freddidierRTE** [comment]
we will see the problem when we will need to implement a new driver , so closing the issue
