### ISSUE TITLE
Use basePath in APIs and nginx redirections consistently accross services

### ISSUE THREAD

**Issue by AlexGuironnetRTE** [opfab/operatorfabric-core#1660]
The swagger.yml files define the paths of the API endpoints for each service. This impacts the generated controllers, the documentation and the generated curl requests (from the documentation). I had to look into how it worked to create a new service & endpoints for external devices and it looks like no two services follow the same logic, making it difficult to know what to do for future services.

### User service

```
basePath: /users
...
paths:
'/users/{login}':
    get:
      summary: Fetch an existing user
...
```

This endpoint is accessible from the outside at `localhost:2002/users/users/{login}` (host + basePath + path). The curl generated from the documentation and the UI call reflect that.

If we try to call this endpoint directly on the users service (without going through nginx), `localhost:2103/users/users/{login}` gives a 404 not found, the correct call is `localhost:2103/users/{login}` (i.e. removing the basePath).

This is because nginx has a rule saying that all calls starting with `users` should be redirected to the users service, after removing the   
Basically the basePath acts as a routing key for nginx to know which service it should forward the request to, and then nginx rewrites the call to remove the basePath as the service expects calls to the endpoint path directly.
To make this work, there has to be a rule in the nginx conf matching the basePath:

```
  location ~ "^/users/(.*)" {
    proxy_set_header Host $http_host;
    proxy_pass http://users:8080/$1;
    proxy_set_header X-Forwarded-For $remote_addr;
  }
```

From [the documentation](https://swagger.io/docs/specification/2-0/api-host-and-base-path/) it looks to like this usage is coherent with the intended purpose of basePath (even though it the documentation example the basePath reflects versions of the API).

### Cards-publication and cards-consultation services

These were bound to be a little different, as here we have one swagger file defining the API for 2 services, and the controllers don't implement a generated API.

So the basePath is defined as `cards`, but that's incorrect for calls to cards-publication. For example for user acknowledgments, a correct call is `http://localhost:2002/cardspub/cards/userAcknowledgement/{id}` while the documentation points to `http://localhost:2002/cards/cards/userAcknowledgement/{id}`

In the nginx conf, there are several re-write rules:

```
  location /cards/ {
    proxy_set_header Host $http_host;
    proxy_pass http://cards-consultation:8080/;
    proxy_set_header X-Forwarded-For $remote_addr;
  }
  location /cardspub/cards/userCard {
    proxy_set_header Host $http_host;
    proxy_pass http://cards-publication:8080/cards/userCard;
    proxy_set_header X-Forwarded-For $remote_addr;
  }
  location /cardspub/cards/userAcknowledgement {
    proxy_set_header Host $http_host;
    proxy_pass http://cards-publication:8080/cards/userAcknowledgement;
    proxy_set_header X-Forwarded-For $remote_addr;
  }
  location /archives {
    proxy_set_header Host $http_host;
    proxy_pass http://cards-consultation:8080;
    proxy_set_header X-Forwarded-For $remote_addr;
  }
```

### Businessconfig service

And finally, businessconfig works in yet another way: there is no basePath, and all paths in the swagger file start with "businessconfig".
And the nginx conf has a rule that has it re-route all calls starting with /businessconfig to the businessconfig service but without changing the endpoint.

So a call to localhost:2002/businessconfig/processes/userCardExamples/i18n is translated directly to localhost:210X/businessconfig/processes/userCardExamples/i18n.

**Comment by AlexGuironnetRTE** [comment]
Note: The first part of the path is what makes the division between controllers. For example, the swagger file for the "Users" service has paths starting with "users", with "groups", with "entities" and with "perimeters", so 4 API classes (to be implemented by Controllers) are generated.

**Comment by AlexGuironnetRTE** [comment]
If we decide to do nothing about that, it might be good to at least point to the information above in the dev documentation in order to save time the next time we have to create new APIs.

**Comment by freddidierRTE** [comment]
too old issue
