### ISSUE TITLE
Add cypress tests for card detail rendering

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#1686]
Add an example  using all the feature "UTILITIES FOR TEMPLATE"  in templateGateway in a card and test it with cypress :
- getEntityName()
- redirectToBusinessMenu()
- isUserAllowedToRespond()
- isUserMemberOfAnEntityRequiredToRespond()
- getEntitiesAllowedToRespond()

Use bundle src/test/resources/bundles/cypress 

Name it with a general name as this template will be used after to test rendering features using handlebars helper

**Comment by AlexGuironnetRTE** [comment]
How about "templating-kitchen-sink" ?

**Comment by freddidierRTE** [comment]
finally it will only be a template for templateGatewayTesting

**Comment by freddidierRTE** [comment]
Finally implementation of test for  : 

1. DetailContext injection
2. TemplateGateway 
3. Handlebars features
