### ISSUE TITLE
Automatic testing OpFab - Kafka implementation

### ISSUE THREAD

**Issue by florisvdmeulen** [opfab/operatorfabric-core#1705]
As DevOps team
I want OpFab automatic be tested
So that I have to execute less manual work
And can release on one way.

Background:
Take a look at "Have a possibility to check/validate the Kafka implementation · Issue #1304 · opfab/operatorfabric-core "
Java projects: test containers.

Acceptance criteria:

Kafka implementation automatic tested
Test result:

no failures found
x test failures found

**Comment by JeroenGommans** [comment]
Issue can be closed. Kafka integration tests were added in #1304
