### ISSUE TITLE
Acknowledgement tests failing randomly on CI

### ISSUE THREAD

**Issue by AlexGuironnetRTE** [opfab/operatorfabric-core#1751]
Some examples:

https://app.travis-ci.com/github/opfab/operatorfabric-core/builds/237866985
https://app.travis-ci.com/github/opfab/operatorfabric-core/builds/237820292

**Comment by AlexGuironnetRTE** [comment]
Error is the same in both cases: 

>  1) Acknowledgment  tests
> 
>        Check acknowledgment for operator 1:
> 
>      AssertionError: Timed out retrying after 4000ms: Expected to find element: `.fa-check`, but never found it. Queried from element: <div#opfab-feed-light-card-cypress-message1.card.light-card-detail.light-card-detail-unselected>
> 
>       at Context.eval (http://localhost:2002/__cypress/tests?p=cypress/integration/Acknowledgment.spec.js:185:55)

**Comment by AlexGuironnetRTE** [comment]
The issue is with adding the "find" command, as in Cypress only the last command is retried (see [documentation](
https://docs.cypress.io/guides/core-concepts/retry-ability#Only-the-last-command-is-retried)).

**Flaky:**
`cy.get(#id of the lightcard).find(.fa-check)` => Cypress finds the lightcard element then retries the find command on this "frozen" copy of the element for 4000ms (standard timeout). Unfortunately, if for some reason the target element of the get is present in a "temporary" state before being refreshed. That's what happens here: on the CI, the POST to the ack service takes a while to respond so when the get looks for the light card just after clicking, it finds it without the ack icon. Then the POST succeeds and the lightcard is updated to display the icon, but it's too late as the find is being retried on the first "version" that the get found.

Correct:
cy.get(#id of the lightcard .fa-check); => this way Cypress retries until it finds an element that fits both the following conditions:
- Id is #id of the lightcard being checked
- Has a descendant with class .fa-check

**Comment by freddidierRTE** [comment]
In this last case , we may  write : 

```
cy.get((#id of the lightcard);
cy.get(#id of the lightcard .fa-check).should(not.exist);
```

**Comment by AlexGuironnetRTE** [comment]
> In this last case , we may write :
> 
> ```
> cy.get((#id of the lightcard);
> cy.get(#id of the lightcard .fa-check).should(not.exist);
> ```

Yes that's also an option, and we'd have to test but I think performance-wise it would probably be similar to `within`... And maybe that's more legible in case of failure.

**Comment by AlexGuironnetRTE** [comment]
Come to think of it, there might still be an issue with:
 
```
cy.get((#id of the lightcard);
cy.get(#id of the lightcard .fa-check).should(not.exist);
```
If the light card briefly appears (without the check) and then disappears, both assertions will pass even though the final display (no light card at all) is not what is expected. That can't happen (I think) with `within`.
