### ISSUE TITLE
API uses number type (implemented as BigDecimal) for integer properties

### ISSUE THREAD

**Issue by AlexGuironnetRTE** [opfab/operatorfabric-core#1836]
Some properties that are integers by definition are typed as `number` in the swagger.yaml definition files for our APIs. As a result, they get implemented as `BigDecimal` in the generated classes or interfaces, which is not optimal and could be misleading.
As stated in [the documentation](https://swagger.io/docs/specification/data-models/data-types/#numbers), the proper type for integers is... `integer`.

**Example:** in the card-publication swagger file (services/core/cards-publication/src/main/modeling/swagger.yaml), all properties regarding pagination such as `numberOfElements`, `totalOfElements` etc. are typed as `number`.
As a result, they are implemented as `BigDecimal`:
- in the client library (client/cards/build/swagger/src/main/java/org/opfab/cards/model/LightCardPage.java)
- in the card-publication service (services/core/cards-publication/build/swagger/src/main/java/org/opfab/cards/publication/model/LightCardPage.java)

**TODO:**
- Go through all the swagger.yaml files and change the type of fields to `integer` when appropriate.
- Adapt java code so it fits the new generated classes/interface
- Test on a running instance for unforeseen side-effects
- Adapt the clientApp (as it relies on client libraries)
- Document the change in a migration guide, as it is going to be a breaking change for users of the client libraries.

**Comment by freddidierRTE** [comment]
Not revelant anymore , code is not generated anymore by swagger
