### ISSUE TITLE
Naming for web-ui properties acting as default values for user settings is misleading

### ISSUE THREAD

**Issue by AlexGuironnetRTE** [opfab/operatorfabric-core#1838]
web-ui properties pertaining to a given screen are usually stored under a key corresponding to the name of the screen. 
For example:

```
  "settings": {
    "infos": {
      "hide": {
        "description": true
      }
    }
```
or 

```
  "feed": {
    "card": {
      "hideTimeFilter": false,
      "time": {
        "display": "BUSINESS"
      },
      "hideAckFilter": false,
      "hideSeveritySort": false,
      "hideAckAllCardsFeature": false
    },
```
In addition, there is a mechanism allowing to provide an instance-wide default value for some users settings by defining a property in web-ui.json with the following convention: "settings.nameOfTheSettingProperty".
For example:

```
"settings.playSoundForAlarm" : true
```
This means for users whose `playSoundForAlarm` setting is not defined, the value will be "true", meaning sounds will be played for the Alarm severity.

These two conventions can be confusing, especially as from the documentation all these properties are listed together (see src/docs/asciidoc/deployment/configuration/web-ui_configuration.adoc).

```
|settings.infos.hide.description|false|no|Control if we want to hide(true) or display(false or not specified) the user description in the settings page
|settings.playSoundForAlarm|false|no|If set to true, a sound is played when Alarm cards are added or updated in the feed

```

More importantly, there is no way of guessing from the documentation that in the case of the "default value for settings" properties, what is expected is a single top-level key "settings.nameOfTheSettingProperty" and not a "nameOfTheSettingProperty" key that is part of the "settings" object (as is the convention for all other properties).

**Proposition:**

Changing the "default value for settings" convention to something like "defaultSetting_nameOfTheSettingProperty".
For example "defaultSetting_playSoundForAlarm".
The underscore instead of the period would avoid confusion with the json format.

**Comment by AlexGuironnetRTE** [comment]
There is also the case of 

|settings.tags.hide||no|Control if you want to show or hide the tags filter in feed page

Which doesn't really seem to fit either convention...

**Comment by freddidierRTE** [comment]
> settings.tags.hide

this parameter is not existing anymore

**Comment by freddidierRTE** [comment]
instead of underscore use .defaultValue

settings.playSoundForAlarm.defaultValue

**Comment by freddidierRTE** [comment]
Close as treated in #3328
