### ISSUE TITLE
asciidoctor gradle task incorrectly marked as up-to-date

### ISSUE THREAD

**Issue by AlexGuironnetRTE** [opfab/operatorfabric-core#1844]
Steps to reproduce:
- Run $OF_HOME/gradlew asciidoctor
- Make some changes to an existing asciidoc source file (under src/docs/asciidoc)
- Run $OF_HOME/gradlew asciidoctor again
Gradle build output: 
> 1 actionable task: 1 up-to-date
And the corresponding html file is not updated with the changes.

If you run `gradlew clean asciidoctor` (or delete the output folder), the asciidoctor is correctly run and the file is updated.

**Comment by freddidierRTE** [comment]
Not reproducible in last version of Gradle
