### ISSUE TITLE
Authorize sending response from entity emitting user card

### ISSUE THREAD

**Issue by OlivierVoron** [opfab/operatorfabric-core#1873]
Linked to #1569, it will be useful if the emitter could also answer to their questions, sent to other parties. It will allow sharing comment and eventual change of mind regarding the response to address, and better interactivity between the emitter and the other parties.

**Comment by freddidierRTE** [comment]
Add a boolean field in state.response in config.json 

Field name : entityEmitterAllowedToRespond

When value is true , the users of the entity having emitted the card can respond .

False by default .
