### ISSUE TITLE
Factorize duplicated utility classes

### ISSUE THREAD

**Issue by AlexGuironnetRTE** [opfab/operatorfabric-core#1938]
Some classes are currently duplicated (sometimes with slight variations) across services. It would be better to share (or at least inherit from) a common version.

- UserExtractor
- CustomExceptionHandler
- WebSecurityConfiguration

Note: We might need to keep a separate version for the Users service as for it "User" is an interface whereas for all the other serivces "User" is a class (from the client lib).
Also, there might be variants for WebSecurityConfiguration depending on whether we're using reactive code or not.

**Comment by freddidierRTE** [comment]
Do it only for CustomExceptionHandler

- WebSecurityConfiguration is specific for each service 
- User Extractor is only present three times , there is very few code and context is different  in the three cases
