### ISSUE TITLE
Docker recreates volumes every time a docker-compose up is triggered

### ISSUE THREAD

**Issue by olivierPigeon-RTE** [opfab/operatorfabric-core#1946]
To recreate the problem, do as following :
   * docker volume list | wc -l  # tells you how many docker volumes exist
   * cd $OF_HOME/config/docker
   * docker-compose up -d
   * docker-compose down
   *  docker volume list | wc -l

Actual: The number of volumes increased
Expected : docker should reuse volumes instead of recreating new ones

**Comment by AlexGuironnetRTE** [comment]
Or if it recreates new ones to start from a clean state,which is kind of what I (maybe wrongly ) expect after a "down", why does it keep the old ones...

**Comment by freddidierRTE** [comment]
to remove all volume , you need to do :  docker-compose rm -fv 
Create a script stopOpfab.sh in config/docker to launch docker-compose down + docker-compose rm -fv
