### ISSUE TITLE
API paths are open by default

### ISSUE THREAD

**Issue by AlexGuironnetRTE** [opfab/operatorfabric-core#1949]
See `WebSecurityConfiguration` classes.

For all APIs the last line in the security configuration is 

`.anyRequest().access(AUTH_AND_IP_ALLOWED);`

Meaning that if the request path doesn't match any of the patterns above, it will be accessible to all users by default. When developing a new endpoint, it means that it will "work" straight away, but it also means that we are more likely to forget to restrict its access if it's necessary.

My suggestion would be for all unmatched paths to be blocked instead. 

Note: We probably can't just delete this line though as it might mess with OPTIONS requests?

**Comment by freddidierRTE** [comment]
at least each request is authenticated , i think it is sufficient for now
