### ISSUE TITLE
Instance-wide default values mechanism for settings properties can be confusing

### ISSUE THREAD

**Issue by AlexGuironnetRTE** [opfab/operatorfabric-core#2029]
There is a mechanism allowing to provide an instance-wide default value for some users settings by defining a property in web-ui.json with the following convention: "settings.nameOfTheSettingProperty".
For example:

```
"settings.playSoundForAlarm" : true
```

This means for users whose playSoundForAlarm setting is not defined, the value will be "true", meaning sounds will be played for the Alarm severity.

This can be confusing for the user as in this case, the settings screen displays an unchecked checkbox for this property, as it reflects the settings value, not the value that is being applied (in this case, the one from web-ui.json).

Steps to reproduce:
- In config/docker/ui-config/web-ui.json, add `"settings.playSoundForAlarm" : true`
- Start a brand new OpFab instance in docker mode
- Log in with operator1
- Go on the settings page : the playSoundForAlarm checkbox is unchecked (because you don't have a value yet for this setting), so you don't expect sounds to be played for this severity
- Send an ALARM card : a sound is played => SURPRISE
- Go back to settings and check the playSoundForAlarm checkbox (This will cause the value for this property to be set to true in your settings)
- Send a new ALARM card  : sound is played (this time that's expected)
- Go back to settings and uncheck the playSoundForAlarm checkbox (This will cause the value for this property to be set to false in your settings)
- Send a new ALARM card : no sound since your setting value (false) overrides the web-ui default (as should be, but confusing because different from the initial behaviour).

Same is true for replayEnabled for example (which was the point reported by @vlo-rte).

It would be good to have a way to tell the user that a default value is being applied (be it from web-ui.json or the last-resort fallback).

When thinking of a solution consider #1838 also.

**Comment by vlo-rte** [comment]
The solution I propose in my pull request do not make a PATCH request. This way, we don't lose the information of whether a particular setting value was a choice from the user or just the default values in "web-ui.json" file.
