### ISSUE TITLE
Update to Angular v13

### ISSUE THREAD

**Issue by AlexGuironnetRTE** [opfab/operatorfabric-core#2054]
Angular v13 is out : https://blog.angular.io/angular-v13-is-now-available-cce66f7bc296

See the update guide : https://update.angular.io/?l=3&v=12.0-13.0

**Comment by freddidierRTE** [comment]
Migration does not work , we need to wait for a fix : https://github.com/angular/angular/issues/44019

**Comment by freddidierRTE** [comment]
Migration does not work , we need to wait for a fix : https://github.com/angular/angular/issues/44019
