### ISSUE TITLE
karma-coverage-istanbul-reporter is deprecated

### ISSUE THREAD

**Issue by AlexGuironnetRTE** [opfab/operatorfabric-core#2198]
Warning in build:

> 'karma-coverage-istanbul-reporter' usage has been deprecated since version 11.
> Please install 'karma-coverage' and update 'karma.conf.js.' For more info, see https://github.com/karma-runner/karma-coverage/blob/master/README.md

**Comment by freddidierRTE** [comment]
as we do not measure coverage on the front , do we really need the tool ?

**Comment by AlexGuironnetRTE** [comment]
Probably not anymore you're right! Shall I remove it and we'll see what happens ?
