### ISSUE TITLE
Feed screen : the spinner is not displayed every time it should

### ISSUE THREAD

**Issue by vlo-rte** [opfab/operatorfabric-core#2199]
The spinner in the feed screen is not displayed every time. 
For example, it happens when you launch several times "./send6xN_TestCards.sh 200". The first time you execute the script, the spinner is displayed but next times, it is not displayed or it can take a long time to be displayed.
(Tested with chrome)

**Comment by quinarygio** [comment]
Not a bug, it just depends on how fast are cards loading, when cards are loading slowly the spinner is not showing
