### ISSUE TITLE
The last line is sometimes truncated in admin screens boards

### ISSUE THREAD

**Issue by olivierPigeon-RTE** [opfab/operatorfabric-core#2202]
In users/entities/groups/perimeters screens, the last line is sometimes truncated as seen below when the user's mouse is on a line.

This is not always the case : to get this, switch between the four menus mentioned above and hover some lines until you get this result.
Once the bug is reproduced, the last line will be truncated when hovering any line until the page is changed or refreshed

![screen](https://user-images.githubusercontent.com/91961842/145071157-4ff116d6-a453-4a2e-a67b-03a0af7a8ae6.png)

![screen2](https://user-images.githubusercontent.com/91961842/145071171-a9a747d4-8123-47ad-ac4f-2fed8a1707a2.png)

**Comment by freddidierRTE** [comment]
we had seen this bug on the past and find no solution do solve it
