### ISSUE TITLE
Add controls on tasks dates when creating a user card

### ISSUE THREAD

**Issue by olivierPigeon-RTE** [opfab/operatorfabric-core#2238]
![screen](https://user-images.githubusercontent.com/91961842/146020600-af5554b9-2802-4279-b3e2-358fd1db5be3.png)

Currently there is no control on tasks time when creating a user card
* force the user to write numbers (letters are also valid for now)
* see if the hour should be 0 to 23 or 0 to 11 plus a checkbox morning/afternooon (some countries are not used to 0-23)

**Comment by freddidierRTE** [comment]
see if we can use https://developer.mozilla.org/fr/docs/Web/HTML/Element/Input/time
