### ISSUE TITLE
No pipe should be displayed in card detail header if no lttd

### ISSUE THREAD

**Issue by AlexGuironnetRTE** [opfab/operatorfabric-core#2248]
OK:
![image](https://user-images.githubusercontent.com/45459065/146166824-3aa29881-1d03-4c31-b6ad-cf6ce5c0ffea.png)
![image](https://user-images.githubusercontent.com/45459065/146166913-05a7a338-475a-4948-9c7e-98243a905ad6.png)

KO:
![image](https://user-images.githubusercontent.com/45459065/146166716-d2ac5aed-5b04-4313-9504-d3272c5f1e82.png)

**Comment by quinarygio** [comment]
The issue does not occurr anymore
