### ISSUE TITLE
Feed screen : "shivering" on chrome when bubble on the right side of the timeline

### ISSUE THREAD

**Issue by vlo-rte** [opfab/operatorfabric-core#2278]
The shivering is very visible when you have "electricity consumption forecast" or "a chart" card open. 
It happens on chrome, not on firefox. You must have one or more bubble(s) on the right side of the timeline and hover it (or them).

**Comment by vlo-rte** [comment]
https://user-images.githubusercontent.com/57365872/146561353-b7daed05-c779-41f7-a9f1-fb7141bde5c7.mp4

**Comment by freddidierRTE** [comment]
too old issue
