### ISSUE TITLE
Possibility to get entity information and the list of all entities

### ISSUE THREAD

**Issue by anouarguesrami** [opfab/operatorfabric-core#2296]
Having the possibility to get the array of entities and another function to get all the information from a specific entity by its id:
could be used to find the role of an entity

**Comment by freddidierRTE** [comment]
So create two methods in templateGateway :+1: 
- getAllEntities()  : return all entities
- getEntity(id) : return an entity with is id 

Modify cypress test src/test/cypress/cypress/integration/CardDetail.spec.js to test this two new methods 

Add in documentation a new chapter in https://opfab.github.io/documentation/archives/3.2.0.RELEASE/docs/single_page_doc.html#_operatorfabric_specific_functions


Coding warning : 
**To avoid coupling internal opfab objects with template do not just give a reference to the entities** , create a new list of object that contains javascripts object based on internal entity object.

Create the new objects by coping field by field (for now we copy all field but we may in the future not doing so )
