### ISSUE TITLE
The 'Try it!' section doesn't work out of the box on macOS

### ISSUE THREAD

**Issue by nrg500** [opfab/operatorfabric-core#2342]
Hi,

The scripts used in the getting started:
`src/test/resources/bundles/loadAllBundles.sh
src/test/resources/perimeters/createAllPerimeter.sh`

Don't run on macOS because they contain shell specific features that the mac shell doesn't have such as negative substring length, double spaces before arguments and the use of "date".

I will be submitting a PR with the changes I needed to make it work.

Note: this is my first time contributing, so please forgive any obvious mistakes and feel free to point out whatever I missed. 😄

**Comment by freddidierRTE** [comment]
You weren't allowed to do it
I add you the permission, you should have received a mail
