### ISSUE TITLE
Only latest uploaded bundle is shown

### ISSUE THREAD

**Issue by MitchelNijdam-Rockstars** [opfab/operatorfabric-core#2401]
In the `getProcesses` API for Businessconfig, it is unclear the response only returns the latest uploaded version per ID. I was expecting to find _all_ process, including previous versions.

![image](https://user-images.githubusercontent.com/35219912/149799743-bcd37942-e3b6-4d5b-a96b-acd5cf053b49.png)

https://github.com/opfab/operatorfabric-core/blob/41d1e0090d109326d116367b428988cfaf4d8a9f/services/businessconfig/src/main/java/org/opfab/businessconfig/services/ProcessesService.java#L91-L93

My suggestion is to either:

1. update the API documentation for this endpoint to explicitly say "List latest uploaded version of existing processes"
2. add an endpoint to retrieve all versions of a given processId
3. both

I'm happy to contribute if you think above solution is feasible.

**Comment by freddidierRTE** [comment]
Point 1 is to be done 
For point 2 , it could be done , it is a question of priority , do you need it ?

**Comment by MitchelNijdam-Rockstars** [comment]
Hey @freddidierRTE 

I was looking for ways to find all versions of a specific template bundle, and the only way was to use `/businessconfig/processes/{processId}?version={version}` in a loop, increasing the version every time until none was found.

It's not that I specifically need a new endpoint, it was just that current endpoints weren't the most efficiënt.

**Comment by freddidierRTE** [comment]
I create an issue for a feature to have the possibility to get all version of a process :  #2404 

I keep this issue for current documentation modification
