### ISSUE TITLE
Monitoring column answers : showing only EntitiesRequiredToRespond

### ISSUE THREAD

**Issue by anouarguesrami** [opfab/operatorfabric-core#2428]
The "Answers" column in the Monitoring screen should display only the EntitiesRequiredToRespond (i.e. the TSOs that can validate a remedial action and not the RSCs).
Please check the attached screenshot.

![image](https://user-images.githubusercontent.com/76995058/150764137-67a028b6-5d63-4ace-bf58-831064f4bc6f.png)

**Comment by freddidierRTE** [comment]
the rules shall be as for detail card : if entitiesRequiredToRespond is present in the card, we use them as the list of entities if not we use entityAllowedToRespond
