### ISSUE TITLE
Monitoring: column filter is lost when deselecting the flag "Cards with response from my entity" 

### ISSUE THREAD

**Issue by quinarygio** [opfab/operatorfabric-core#2463]
In Monitoring screen, setting a filter on one column of the table and then deselecting the flag "Cards with response from my entity" loses the filter on the column, sorting instead is kept

**Comment by vlo-rte** [comment]
Impossible to reproduce this behaviour. Maybe a previous update has solved the problem.

**Comment by vlo-rte** [comment]
Giovanni has confirmed it is solved, so I close the issue.
