### ISSUE TITLE
Card summary and card title showing Hex code instead of special characters

### ISSUE THREAD

**Issue by anouarguesrami** [opfab/operatorfabric-core#2472]
After applying the migration script of the 3.0.0 release, the special characters in the card title and summary, like "/" or "<", are replaced in the UI by the corresponding Hex code. This is an example of an OpFab card with this bug : 

`{
	"_id" : "MYAPP_MYPROCESS_pid_10",
	"data" : {
		"cardId" : 10,
		"timeframe" : "W",
		"timeframeNumber" : 15,
		"startDate" : {
			"nano" : 0,
			"epochSecond" : 1585951200
		},
		"endDate" : {
			"nano" : 0,
			"epochSecond" : 1586469600
		},
		"receivedAt" : {
			"nano" : 663000000,
			"epochSecond" : 1585836032
		},
		"typeMerge" : "Validated",
		"links" : {
			},
		"specificUapLinks" : {
			},
		"comment" : null
	},
	"endDate" : ISODate("2020-04-10T22:00:00Z"),
	"groupRecipients" : [
		"GROUP1"
	],
	"orphanedUsers" : [ ],
	"process" : "MyProcess_pid_",
	"publishDate" : ISODate("2020-04-02T14:00:33Z"),
	"publisher" : "MY_APP",
	"recipient" : {
		"type" : "GROUP",
		"identity" : "GROUP1"
	},
	"severity" : "INFORMATION",
	"shardKey" : 0,
	"startDate" : ISODate("2020-04-03T22:00:00Z"),
	"state" : "state",
	"summary" : {
		"key" : "cardFeed.summary",
		"parameters" : {
			"summary" : "MYPROCESS - W-1 process W15 04/04/2020-10/04/2020 (CET/CEST) - STATUS"
		}
	},
	"tags" : [
		"myprocess",
		"myprocess_state"
	],
	"timeSpans" : [
		{
			"start" : ISODate("2020-04-02T14:00:32.663Z"),
			"end" : ISODate("2020-04-10T22:00:00Z"),
			"display" : "BUBBLE"
		}
	],
	"title" : {
		"key" : "cardFeed.title",
		"parameters" : {
			"title" : "My Process Title"
		}
	},
	"uid" : "f464ef8f-f568-4565-90b3-49857fee9e85",
	"userRecipients" : [ ],
	"processInstanceId" : "MyProcess_pid_10",
	"processVersion" : "0.1",
	"publisherType" : "EXTERNAL",
	"usersReads" : [
		"user1"
	],
	"usersAcks" : [
		"user1"
	],
	"summaryTranslated" : "cardFeed.summary.MyProcess_pid_.0.1",
	"titleTranslated" : "cardFeed.title.MyProcess_pid_.0.1"
}`

**Comment by vlo-rte** [comment]
(This issue is related to issue #2501)
I propose to replace {{xx}} with {{{xx}}} in the i18n.json files of your bundles. This way, special characters won't be encoded by handlebars. I think you will have to relaunch the migration script after these modifications.

(For more information, you can see also : https://github.com/jamesarosen/ember-i18n/issues/77)

**Comment by anouarguesrami** [comment]
Thank you for your reply, it works!
I close the ticket.

**Comment by anouarguesrami** [comment]
Unfortunately the problem persists. Using 3 curly braces {{{xx}}} works when it comes to Handlebars file, but in the i18n.json file it does'nt (please see the screenshot bellow)
![cardFeed](https://user-images.githubusercontent.com/76995058/153405396-3ac9f388-35a1-4730-b9a1-42639701dd8f.png)

Here is some information about the card and the associated bundle:
[template.zip](https://github.com/opfab/operatorfabric-core/files/8040947/template.zip)
[i18n.zip](https://github.com/opfab/operatorfabric-core/files/8040948/i18n.zip)
[config.zip](https://github.com/opfab/operatorfabric-core/files/8040949/config.zip)
[card.zip](https://github.com/opfab/operatorfabric-core/files/8040951/card.zip)
