### ISSUE TITLE
Excess of memory limit in Archives and Logging screens with OperatorFabric 2.11.0.RELEASE

### ISSUE THREAD

**Issue by SaschaEschmann** [opfab/operatorfabric-core#2490]
Dear OpFab colleagues,

We identified that when the number of results in the Archives and Logging screens is around 50k, the search fails without message to the user, please find below the trace from the console :

`"org.springframework.data.mongodb.UncategorizedMongoDbException: Command failed with error 16819 (Location16819): 'Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting. Aborting operation. Pass allowDiskUse:true to opt in.' on server prod-usy-mongodb:27017. The full response is {\"ok\": 0.0, \"errmsg\": \"Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting. Aborting operation. Pass allowDiskUse:true to opt in.\", \"code\": 16819, \"codeName\…ynchronousChannelStream.java:233)\n\tat java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)\n\tat java.base/sun.nio.ch.Invoker$2.run(Invoker.java:219)\n\tat java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:829)\n"`

**My questions are :**

- Is it still the case (error without message to the user) with the latest versions of OperatorFabric ? 
- Did you manage some performance improvements since the 2.11.0 ? Mainly related to the memory limit (104857600 bytes) ?

Kind regards,

**Comment by freddidierRTE** [comment]
Solve partially by #2505 

Still problem when using collapsed mode , or when going at end of the list when there is a lot of card

**Comment by freddidierRTE** [comment]
Not present anymore
