### ISSUE TITLE
Add method in userTemplateGateway to set/get startDate,endDate, lttd 

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#2495]
Add in userTemplateGateway the following methods 

- getStartDate() --> in epochMs
- getEndDate()   --> in epochMs
- getLttd() --> in epochMs
- setStartDate(epochMs)
- setEndDate(epochMs)
- setLttd(epochMs)

Use it in question usercard example to set the startDate , endDate and lttd . For example , startDate could be the next round hour and endDate could be 8 hours later and lttd 4 hours after startDate 

Add a cypress test (using the clock feature to be in a specific point in time) 

Add in documentation (in chapter https://opfab.github.io/documentation/archives/3.4.1.RELEASE/docs/single_page_doc.html#user_cards)

**Comment by quinarygio** [comment]
Implemented a cypress test without using cy.clock() feature because othewise it was not working correctly..
