### ISSUE TITLE
User card , bug when using \ in title or summary in example cards

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#2509]
send card using via the ui using  base example --> message 

Add a \ in message , it does not work 

Solution : replace \ by \\ in the template ?  in usercard component ?  

What happens when editing cards ?

**Comment by vlo-rte** [comment]
I think this issue is solved by upfate for https://github.com/opfab/operatorfabric-core/issues/2472
Please check. Thank you.

**Comment by freddidierRTE** [comment]
I confirm it solve  #2472
