### ISSUE TITLE
Compatibility between OperatorFabric and Keycloak 16.1.1 released

### ISSUE THREAD

**Issue by SaschaEschmann** [opfab/operatorfabric-core#2530]
Dear OperatorFabric's colleagues,

Could you tell me (or check) if OperatorFabric is compatible with the currently latest version of Keycloak 16.1.1 (https://www.keycloak.org/2022/01/keycloak-1611-released) ?

The version of OperatorFabric that we are currently using is 2.11.0 RELEASE.

Thank you in advance.

Kind regards,

**Comment by quinarygio** [comment]
Hello
I checked the compatibility with  Keycloak 16.1.1 and didn't find any issue. 

Regards

**Comment by SaschaEschmann** [comment]
Dear @quinarygio ,
Thank you very much for your feedback.
Best regards,
