### ISSUE TITLE
Add child cards in archive detail cards  

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#2560]
As for card in feed , process child cards when rendering a card in archives 

We need to retrieve child cards from mongoDB taking into account that a child card : 
- can be updated 
- can persist or not when updating parent card depending on the value of keepChildCards 

For the child update , the rule is : take the last update (revelant to the parent card )

To ease the search in db , i could be interesting to store the date when a card is deleted (adding a deletionDate parameter in the archive card) . So to search child card , we can do : 

Having the parent card take all card with parentCardId == parentcard.id and (deletionDate == null OR deletionDate > parentcard.publishDate) and ( parent.deletionDate ===null OR publishDate < parent.deletionDate )

**Comment by quinarygio** [comment]
Adding a deletionDate to archived cards what shall we do to migrate previuos database ? deletionDate would be null for all previous archived cards
