### ISSUE TITLE
Card detail : withe border on acknowledge button sometimes

### ISSUE THREAD

**Issue by vlo-rte** [opfab/operatorfabric-core#2599]
![image](https://user-images.githubusercontent.com/57365872/154736383-c0270d92-a4d1-4d6e-813e-1ef5d1081b5f.png)

It seems to happen if you open the card "electricity consumption forecast", you click on the "grid", then you close the card with escape touch of keyboard and then open another card.

**Comment by quinarygio** [comment]
The issue does not occurs anymore. It seems It was solved by PR #2625 that concerned card detail dismissal.
