### ISSUE TITLE
New option to consider acknowledgment at the entity level 

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#2772]
Add an option in state definition  (in config.json)  named : consideredAcknowledgedForUserWhen.

This option shall be used to define if a card is considered as acknowledged in the feed or not.

Possible values : 

-  userHasAcknowledged
-  oneUserEntityHasAcknowledged
-  allUserEntitiesHasAcknowledged

If the card is sent only to user or group, it is considered acknowledged if user has acknowledged whatever the configuration in state definition.

For testing, use operator4_fr and activity area.

Add in documentation a specific chapter regarding acknowledgement.

This implies to process the acknowledged received via the subscription to update cards in the feed.

**Comment by vlo-rte** [comment]
In order to avoid confusion and after discussion with Frederic, I propose to rename :
oneUserEntityHasAcknowledged -> oneEntityOfUserHasAcknowledged
allUserEntitiesHasAcknowledged -> allEntitiesOfUserHasAcknowledged
