### ISSUE TITLE
Find a way to prevent having 2 tabs connected on OpFab with different users

### ISSUE THREAD

**Issue by olivierPigeon-RTE** [opfab/operatorfabric-core#2804]
Since #2668 a same user cannot have several sessions at the same time, but it is still possible to open 2 tabs in the same browser with different logins. It should not be allowed as there can be only one token per browser, so the first session will be replaced by the second one but the user name remains unchanged, which can be misleading.

Idea : add a boolean in the local storage to tell if  a session is already opened in the browser

Warnings : If the local storage is used, it should handle :
 1. cases where the user does not log out properly (closing the tab, the browser, connection lost, ...)
 2. it must still be possible to login on opfab deployed on different machines in 2 tabs of the same browser

**Comment by freddidierRTE** [comment]
Have a look to https://blog.bitsrc.io/4-ways-to-communicate-across-browser-tabs-in-realtime-e4f5f6cbedca
