### ISSUE TITLE
Feed screen : No spinner when it takes time to load a card 

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#2820]
To reproduce 

./sendCard.sh defaultProcess/contingenciesBig.json

Connect with operator1_fr with firefox 
Set network to GPRS 
Click on the card in feed , the card take more than one second to load but there is no spinner

**Comment by vlo-rte** [comment]
The problem occurs if no card is already open and then if you try to open the big card, with slow network.
I also remarked that the log message "WARNING card not found." is written every time you close a card, and also when you open a card (no need slow network for that).

The selector "selectCardStateSelectedWithChildCards" returned a null card when no card is found but also when the card in the AppState is set to "cardInitialState". So I had to find a way to make a difference between notions of "cardInitialState" and "null card" in this selector.
