### ISSUE TITLE
Hello and one question

### ISSUE THREAD

**Issue by AJ1040968** [opfab/operatorfabric-core#2913]
Hello operator fabric team, i know you, i'm M'Barek BENDAOUD, i have already contributed in this project during 2020, im working actually as techLead for totalEnergies, we are scoping the utilization of opfab to launch a new MVP to monitor parks of renewal energy (solar, wind ...) around the world.

i have a question, h**ave you already estimated the amount of work to split the 4 backend services of opfab in independent repositories** ?, 
this is a perquisite for us to integrate independent CICD pipeline to each services and add ours custom services on top of.

**Comment by freddidierRTE** [comment]
Hello M'Barek 

We have not estimated the amount of work as we never had this need .

Could you just use the docker provided on dockerhub instead of spliting the repository ? Do you need to rebuild the code ? 

The best would be to have a call to exchange on your needs

**Comment by AJ1040968** [comment]
Hello Frederic, 
yes , we need to rebuild the code because we have many custom tasks to develop,  also is better for ou CICD to be on small independant repository than a big global one, especially that we target kubernetes for deployment ,

yes for sure, we can have a call to discuss it , can you tell me your availability ?
