### ISSUE TITLE
Refactor jar names created  for services

### ISSUE THREAD

**Issue by olivierPigeon-RTE** [opfab/operatorfabric-core#2923]
Jar files for users-service, cards-consultation-service, card-publication-service and business-service have the word "business" in their names for no reason

Remove "business" word in : 
* settings.gradle
* service.gradle
* run-all.sh
* ...

**Comment by AlexGuironnetRTE** [comment]
For what it's worth... here are other hard-coded names that gave me trouble in the past in case you feel like fixing them ;-)

https://github.com/opfab/operatorfabric-core/issues/1801
