### ISSUE TITLE
Add map to Opfab page when no card is selected

### ISSUE THREAD

**Issue by JeroenGommans** [opfab/operatorfabric-core#2950]
**Note**. This is an experimental feature and might not make it into the final product

The idea: When Operator Fabric does not show the card details screen, there is a large empty space right of the feed. The idea is to have a geographical map drawn into this empty space. This map should then be able to show the location of current problems on the net. For example, it could show the current congestions in the net.

![opfab-map](https://user-images.githubusercontent.com/51113917/166646796-2e61c8ff-b49b-4919-91c3-28660bb91bb5.png)

**Comment by florisvdmeulen** [comment]
I've missed the roadmap discussion. Can you tell me if this has passed the discussion?

**Comment by JeroenGommans** [comment]
Yes, it is placed on the Short Term Roadmap, see [OperatorFabric Roadmap](https://opfab.github.io/pages/roadmap.html)

**Comment by JeroenGommans** [comment]
@freddidierRTE , what do you think looks best? Should the map be below (more logical to me) or at the filter level (use more screen estate)? 

Map above the filter:
![map-above-filter](https://user-images.githubusercontent.com/51113917/172353903-0ef4644d-99d7-47d7-a3f7-cb3322a1296e.png)

Map at the filter:
![map-at-filter](https://user-images.githubusercontent.com/51113917/172353995-24b225f5-9711-4055-8b08-7b21b0cbadee.png)
