### ISSUE TITLE
Mouse cursor is not the good one in different places

### ISSUE THREAD

**Issue by olivierPigeon-RTE** [opfab/operatorfabric-core#2997]
Change the mouse cursor on the business period buttons above the timeline to set it like other buttons
![screen](https://user-images.githubusercontent.com/91961842/168559732-627e2e7e-cc73-44cd-9235-be71e4a99831.png)

Same thing for the cards titles and summaries in the feed

**Comment by vlo-rte** [comment]
Same problem for the button day/night mode.
