### ISSUE TITLE
geomap: need to handle the case where multiple cards are shown at the same location

### ISSUE THREAD

**Issue by JeroenGommans** [opfab/operatorfabric-core#3138]
(copied from Alliander Jira HMI-1566):

**As** user 
**I want to** be able to access all cards in one location
**So that** I can see all the cards I need

**Background**

There will be more than one card in one location. With the current implementation only one card is shown.

We need a popup in which the other cards in the same location can be accessed

**Acceptance criteria**

When there are more than one cards in one location, the popup indicates that there is more than one card

There is an option to cycle through all the cards

**Open points**

How to show that there is more than one card?

Do we do a list of cards? 

Like the bundle? (Much space needed)

A condensed list, where when you click on a row, the list is expanded to show the other elements?

Do we cycle through them with arrows? Do we have a list?

**Comment by freddidierRTE** [comment]
done in #4126
