### ISSUE TITLE
Add generic loader for cards 

### ISSUE THREAD

**Issue by bengoutaeli** [opfab/operatorfabric-core#3190]
Loader before the displaying of the card. Appears after a long loading (lot of treatments related to the card) .

Example : 
![image](https://user-images.githubusercontent.com/78432948/174601213-3be1490b-9516-4880-a2a4-b54e4c76215c.png)

@freddidierRTE

**Comment by freddidierRTE** [comment]
Add two method in templateGateway 
displayLoadingSpinner()
hideLoadingSpinner()

Add in documentation 
Add a cypress test using kitchenSink.handlebars --> Add a button "test spinner" to launch the spinner , when the user click on the button it show the spinner for two seconds
