### ISSUE TITLE
Only one username visible per group on realtime users dashboard 

### ISSUE THREAD

**Issue by geppyz** [opfab/operatorfabric-core#3221]
On the realtime users dashboard we would like to have an option to show 'all' online usernames per group.
Right now you can see a number of the amount of users that are logged in. 
After this number, is a list of usernames, however only the first one is shown. 
<img width="252" alt="Schermafbeelding 2022-06-27 om 17 27 12" src="https://user-images.githubusercontent.com/18466477/175977595-4b510f41-b483-41ac-96e9-dbe2fd08c27e.png">

**Comment by freddidierRTE** [comment]
Solution would be to add all values as soon as the number of characters does not exceed n . 
n is to be define by testing 
If the number of characters exceed n --> three dot and a popover to show all values
