### ISSUE TITLE
Add device configuration active status 

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#3298]
The devicesConfiguration shall contains a new field named : "enable"
Defaut  value is true

When the field is set to false , the external-device : 
- shall not send any sound to this device (the API shall return an error code  400 + a message  when trying to send a sound to a disabled device)
- shall not send any watchdog 

New endpoints permit to enable/disable the device : 
-configurations/devices/enable
-configurations/devices/disable

Modify actual karate tests src/test/api/karate/externaldevices/ to test this behavior

Add an administration screen to set this value to true/false in external device configuration menu  : Add like for administration screen , buttons on top of the page to switch between : "user configuration" (the actual screen)  and "device activation" 

Add cypress test for administration

To save the configuration , user have to click to a button (no automatic saving)

Modify documentation accordingly

**Comment by olivierPigeon-RTE** [comment]
after a discussion, the saving is automatic when clicking on a checkbox
