### ISSUE TITLE
[Card consultation] Add archive endpoint

### ISSUE THREAD

**Issue by davidbinderRTE** [opfab/operatorfabric-core#33]
Part of #52 user story.

Create an entry point to access archiveCard mongo collection.

The collection will be queried throught a Spring mongo reactive repository.

The Http routing to the controller is to be defined in  **ArchiveCardRouteConfig** (see **CardRouteConfig** and **CardOperationRoutesConfig** as an example).

Different filters are to be implemented, a custom repository may be needed see **CardRepository** for deep repository customization.

**Comment by AlexGuironnetRTE** [comment]
Implemented in OC-44
