### ISSUE TITLE
User cards: Permit to add a list of recipients via the template & user choice

### ISSUE THREAD

**Issue by anouarguesrami** [opfab/operatorfabric-core#3408]
EntityRecipients in a User card is currently set either via template or user choice. We would like to have the possibility to set this field via both possibilities.

**Comment by freddidierRTE** [comment]
so we change the behavior of the actual method define in https://opfab.github.io/documentation/current/reference_doc/#set_recipients_via_code

If we set recipient via code and activate the recipient choice for user  , the resulting list of recipient is the addition of the two list 

Modify documentation accordingly 
Add an example in existing usercard
