### ISSUE TITLE
Simplify Card sending 

### ISSUE THREAD

**Issue by Haigutus** [opfab/operatorfabric-core#3424]
At the moment a lot of the card is defined in the static configuration, but to enable the sending system easily modify the card/message on the go, it would make sense that card configuration is used only as fallback if that data is not in the card.

To be more precise for now I would like to be able define the card title and description directly in the card. 

Reference example:
The form that the archived card looks at retrieval

![Screenshot_20220728-074850.png](https://user-images.githubusercontent.com/11408965/181423676-b9f6e92b-b262-40ad-b51e-2ae16a5f6255.png)

**Comment by freddidierRTE** [comment]
If you want to define a  totally dynamic title or summary , you can configure you i18n.json as follow : 

```
{
		"title": "{{myTitle}}",
		"summary": "{{mySummary}}"
  }
```

When you send the card you set  :  
```
	"title": {
		"key": "title"
                "parameters" : { "myTitle": "My custom title for this card" }
	},
	"summary": {
		"key": "summary"
                "parameters" : { "mySummary": "My custom summary for this card" }
	},

```

**Comment by Haigutus** [comment]
Thanks, it seems exactly what I was looking for
