### ISSUE TITLE
Add card sorting by start and end date

### ISSUE THREAD

**Issue by Haigutus** [opfab/operatorfabric-core#3565]
Currently it is possible to sort cards by priority and creation date, but we are creating cards for future events and would like to sort the list so that the card which end date is closest is the first one, thus enabling operators to see the cards in the order they must be carried out, or were supposed to be carried out.

So I would like to ask, that it would be possible to sort cards by 1. start date and 2 end date

**Comment by Haigutus** [comment]
Also the default sorting option should be configurable for the UI form application settings

**Comment by freddidierRTE** [comment]
If i understand well , it means having two new options :  

![image](https://user-images.githubusercontent.com/58251627/190972781-0d336a3b-2b05-4ab1-8bd4-fb5a06d70cad.png)

Regarding default value , i do not think we need to define this in the settings as when the user change the sorting value , his choice is memorized on the browser . So if the user disconnect and reconnect back later , he keeps the  sorting option as it was before  (there is the same mechanism for filtering )

**Comment by Haigutus** [comment]
- Yes those two options would be great
- I would still see sense that one could configure all default filters globally. Depending on system use case, it would mean that each time new user as a first thing needs to change the filter manually

**Comment by freddidierRTE** [comment]
So for default fitler , instead of having it in the each user settings i would proprose to define default filter at the instance level in the web-ui.json file.

For example : 

```
 "feed": { 
 defaultSort : 'startDate',
 defaultFilter: 'ack' 
}

So when the user first connect , he will have the value define in the web-ui.json

**Comment by Haigutus** [comment]
Yes, that would be perfect, my wording was bad, on instance setup level was exactly what I was thinking

**Comment by freddidierRTE** [comment]
ok , i will separate in two issues , keep this one for start and end date sorting and create a new one for instance settings default configuration
