### ISSUE TITLE
[Configuration] Put build scripts in compliance with gradle 5.x

### ISSUE THREAD

**Issue by davidbinderRTE** [opfab/operatorfabric-core#36]
See #34 
Todo : 
 * change wrapper configuration
 * remove or update visteg plugin

**Comment by rlg-rte** [comment]
The project gradle version is 5.1.1 now.
cf commit a03be32d03dd6cd8a533e344f63e999875065414 
labeled: [Build] uprades to version 5.1.1 of gradle

**Comment by davidbinderRTE** [comment]
Tests does not compile any more: lombok annotation are not anymore processed in tests.
