### ISSUE TITLE
Disable footer when using iFrames

### ISSUE THREAD

**Issue by lhazenoot** [opfab/operatorfabric-core#3620]
Right now there is a footer shown when using iFrames. We would like to be able to make this configurable, so that the iFrame content is shown in full screen and has more space. Default behaviour will remain the same (with footer).

![Footer with iframe in OpFab](https://user-images.githubusercontent.com/91895080/192260217-dde6e005-e50e-41ff-b4c3-03b32394fb7e.png)

**Comment by freddidierRTE** [comment]
You can simply remove this default behavior , we do not need this footer (But be careful to keep it in other screens)
