### ISSUE TITLE
Feed date filter : time fields should not be white

### ISSUE THREAD

**Issue by vlo-rte** [opfab/operatorfabric-core#3633]
Currently we have : 
![image](https://user-images.githubusercontent.com/57365872/192319840-cb3a30bb-43c4-4c95-a794-19671417203c.png)

Time fields should be gray, for example like : 
![image](https://user-images.githubusercontent.com/57365872/192320039-f4bd4004-6747-47bc-bd6a-20e69072f355.png)

**Comment by freddidierRTE** [comment]
Not relevant anymore , datepicker component has been changed
