### ISSUE TITLE
Entity acknowledgment should mark the card as acknowledged for all users of the entity

### ISSUE THREAD

**Issue by quinarygio** [opfab/operatorfabric-core#3731]
Example : 
- operator1_fr is connected and have detail card open but card not ack so button ack is present

- operator4_fr connect and ack card operator1_fr is watching
Having the same entity as operator1_fr
 card should be considered as ack for operator1_fr
 and the button shall be changed to "Cancel acknowledgment".

Think on how to handle the unacknowledgment : when a user unacknowledge a card, the card should be unackowledged for all users of the entity or not ?

**Comment by freddidierRTE** [comment]
I do not thing this use case make sense in real life so i propose to simplify :  when consideredAcknowledgedForUserWhen is set to  OneEntityOfUserHasAcknowledged or AllEntitiesOfUserHaveAcknowledged we do not show the unacknowledge button 

 If in the future we need to unacknowledge at the entity level we will see how to deal with it

**Comment by Jeltel** [comment]
We're experiencing the same issue.
We have lots of cards and when @geppyz acknowledge them, other users still see those cards.

**Comment by freddidierRTE** [comment]
as we decide to not cancel at the entity level , the issue is now : 


    operator1_fr is connected and have detail card open but card not ack so button ack is present

    operator4_fr connect and ack card operator1_fr is watching
    Having the same entity as operator1_fr
    card should be considered as ack for operator1_fr
    and the button ack shall disappear
