### ISSUE TITLE
Automatic deletion of cards after an expiration date time has been reached

### ISSUE THREAD

**Issue by geppyz** [opfab/operatorfabric-core#3762]
Sometimes a card is sent to OpFab, but it is only "valid" for a certain amount of time. When this time has passed, we would like to have the card disappear from the card feed (but stay in the archive).

**Comment by OlivierVoron** [comment]
Hello, it is very good idea. Maybe we should add the characteristic 'lifespan' to each notification. When it is reached, the notification is automatically put in the archive (in fact it is already, but will be removed from the current feed).
My proposition is to have a different characteristic as for some business rules, for example, you should keep a notification one year after date of publication.

**Comment by freddidierRTE** [comment]
yes adding a new field in the card would be the solution 

For the name of this field , i would suggest : automaticDeletionDate ? 

Other ideas ? 

deletionDate is already use in the archive (representing the effective deletion date)

**Comment by quinarygio** [comment]
What about naming the new field : "expirationDate"

**Comment by geppyz** [comment]
Another possibility would be to implement a configuration flag on application level. When for example the config has been set to 'autoDelete' = true, then all cards containing a set endDate will be removed. However that could lead to undesired deletions for older cards that might not have had this construction in mind.

**Comment by geppyz** [comment]
We also think "expirationDate" is a good name 👍
