### ISSUE TITLE
Search filter in the Card Feed

### ISSUE THREAD

**Issue by lhazenoot** [opfab/operatorfabric-core#3768]
Add a search filter in the card feed that finds cards based on card title and summary (and maybe other contents of the cards). The search filter will be placed next to the feed-filter and feed-sort option. 

![Place to add search filter](https://user-images.githubusercontent.com/91895080/197967832-70711833-e829-4f75-8063-6947419123c0.png)

**Comment by freddidierRTE** [comment]
Ok for me.  Add an option in web-ui.json to show/hide the search filter
