### ISSUE TITLE
Identify security event in current logs of opfab micro-services for security analysis

### ISSUE THREAD

**Issue by OlivierVoron** [opfab/operatorfabric-core#3799]
Need to analyse the security events that occur on OperatorFabric to identify if some strange behaviour is detected
Used for forensics and post-analysis
Complementary to classical Web protection and analysis
Need to capture also 'exception' or 'wrong access errors', not only security token oriented but also mismatch error

**Comment by freddidierRTE** [comment]
Closed as there is now security logs in services
