### ISSUE TITLE
Geomap does not show circles on the map 

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#3988]
To reproduce : 

- start a new clean opfab instance
- load default conf
- send the 6 test cards 
- Open opfab with operator1_fr 
- You shoud see the map with the blue point on Arnhem 
- Open process State card 
- Close the card 
- You see again the map but you do not see anymore the blue circle and the view point is set to default instead of zooming on Arnhem

**Comment by lhazenoot** [comment]
Update: 
I have looked at this bug and found out that it only happens when all the cards in the cardlist are readed.
