### ISSUE TITLE
Lttd not correct when creating a usercard 

### ISSUE THREAD

**Issue by quinarygio** [opfab/operatorfabric-core#4148]
When creating a usercard with lttd not visible, the lddt date should be set when sending the card not when preparing the preview of the card.
To reproduce: create a "Incident in progres" usercard, open the preview and wait. You will see lttd counter is started and when sending the card the remaining time to decide depends on when the preview was done.

**Comment by freddidierRTE** [comment]
It is not really a bug as lttd is set as a date and not as a duration , so correcting that  would mean add a new parameter duration to the usercard in the front and a way of "stopping the time" in the preview
