### ISSUE TITLE
Authorized IP addresses : the format should not accept space character

### ISSUE THREAD

**Issue by vlo-rte** [opfab/operatorfabric-core#4244]
If you set for example : 
![image](https://user-images.githubusercontent.com/57365872/220325741-919f87bf-5f0f-42c3-a145-58ecf013eb97.png)

it will be stored in database : 
![image](https://user-images.githubusercontent.com/57365872/220325819-78a8f1bc-be04-4f36-8d39-3aeb47051f14.png)

**Comment by freddidierRTE** [comment]
The feature has been removed
