### ISSUE TITLE
Authorize @ character for user login account

### ISSUE THREAD

**Issue by OlivierVoron** [opfab/operatorfabric-core#4295]
We use an external Identity provider with Keycloak and the user login account created and used for connection to Opfab is an email address. A control in Opfab don't authorize the use of '@' in login account.

The modification should authorize the use of email address as login account for the user

**Comment by freddidierRTE** [comment]
So issue is only control that there is at least one character in the login
and remove spaces at the end  to be consistent with https://github.com/opfab/operatorfabric-core/pull/4217
