### ISSUE TITLE
Special characters in id fields : cypress tests and/or forbid characters 

### ISSUE THREAD

**Issue by vlo-rte** [opfab/operatorfabric-core#4339]
Related to this issue : https://github.com/opfab/operatorfabric-core/issues/4336
Add a test (or use an existing test) to put a space character in the processInstanceId field and try to open the card (be careful, before the update for the bug #4336, the card could be displayed for 1 second (approximatively) and then it disappeared and it is replaced by the spinner endlessly, so we have to take into account this point in the test).

Take into account other fields that could be a problem, like stateId for example. 

The following characters are used in production 
        « _ » 
        « : »
        « - 
        «  » 
        « (  » 
        « )  » 
        « ; » 
        « . » 

  #, ? et / are not used so we should prohibit them  

---> To be confirmed

**Comment by freddidierRTE** [comment]
The issue content is : 
Do not authorize anymore **#**, **?** and **/** in process and processInstanceId fields of the cards.

The control is to be done in the card publication service
