### ISSUE TITLE
The "Process" drop-down list is not displayed when a user has no rights on any process

### ISSUE THREAD

**Issue by anouarguesrami** [opfab/operatorfabric-core#4349]
The Logging menu interface does not display correctly because of the missing "Process" Drop-down list, when a user has no rights on any process.

![Screenshot from 2023-03-22 13-59-58](https://user-images.githubusercontent.com/76995058/226931743-66ca9084-8742-429b-b4b2-05a3e1ab50e4.png)

**Comment by vlo-rte** [comment]
Hello @anouarguesrami ,
I cannot reproduce, when a user has no right on any process, I see : 

![image](https://user-images.githubusercontent.com/57365872/229873403-a53bf7a6-8145-4ff7-8881-71bcc487572a.png)

**Comment by freddidierRTE** [comment]
To reproduce : 
- Connect via admin account
- Add a new group : 
![image](https://user-images.githubusercontent.com/58251627/230386343-f2a7afea-1914-48bc-ae37-969e21de32fd.png)

- Affect the group to the admin account
- Reload 
- Go to logging page
