### ISSUE TITLE
As an Operator, I want to filter the feed to focus on specific relevant cards

### ISSUE THREAD

**Issue by davidbinderRTE** [opfab/operatorfabric-core#45]
The feed needs to be filtered, there is two kind of filters:
- filters which affects purely rendering
  - severity filter (one toggle per severity)
  - see mine/see others toggle
- filters which affects the cards wich the operator is updated with (See #22)
  - date filter (mandatory filters)
  - stick to clock (filter constantly evolve following clock ticks)

The latter needs specific server side behaviour for optimisation.

**Comment by AlexGuironnetRTE** [comment]
Implemented (except see mine / see others toggle as there is no need for it so far)
