### ISSUE TITLE
Grouped cards : blue arrow should not be displayed if only one card ?

### ISSUE THREAD

**Issue by vlo-rte** [opfab/operatorfabric-core#4632]
Currently, the blue arrow is always displayed, even if there is only one card in the group. Maybe it would be better to not display it in this case ?
To be discussed

**Comment by geppyz** [comment]
Agree, would be better to only show the arrow if there is more then one card.

**Comment by vlo-rte** [comment]
Hi Gerben,
Ok thank you for your comment.
If you agree, I can assign the issue to you or a member of your team ? Or we can do it, as you wish.
Have a good day
