### ISSUE TITLE
automaticPinWhenAcknowledged error in browserconsole

### ISSUE THREAD

**Issue by geppyz** [opfab/operatorfabric-core#4696]
Hi all, I'am getting a javascript error in my browser console while having the Operator Fabric dashboard open.

After a while I am seeing the following error in my console:
<img width="1728" alt="Scherm­afbeelding 2023-07-06 om 12 52 11" src="https://github.com/opfab/operatorfabric-core/assets/18466477/3dcf1e99-ee5d-4812-8d57-cdcbe3d873e4">

I'm using Edge 114.0.1823.67 on MacOS 13.4.1 with Operator Fabric 3.15.1.

**Comment by freddidierRTE** [comment]
A least we can correct this error
