### ISSUE TITLE
Process monitoring screen - experimental feature

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#4697]
![image](https://github.com/opfab/operatorfabric-core/assets/58251627/7426454c-cceb-4c82-9b89-6dc2ca88227a)

- The list is not based on card in UI memory(lightcardstore) but on a request to the back , the request is done every 5 seconds to update the table.

- The list of column shall be defined by configuration, it shall be able to mix standard card field and business card field(data.*) , first approach : configuration defined in web-ui.json . 

Structure example : 
```
processMonitoring: {
  [ 
  { "field": "startDate", "colName": "Start Date", "size": "50px"},
  { "field": "titleTranslated" , "colName": "Title", "size": "5%"},
  { "field": "data.myfield", "colName": "My field", "size": "5%"},
  { "field": "summaryTranslated", "colName": "Summary" , "size": "100px"},
  { "field": "data.myfield2", "colName": "My second field" , "size": "100px"}
]
}
```
size field shall be css syntax 

- The severity column is always present (not configurable) 
- No column answers (i.e , we do not deal with child card on this iteration) 
- The back endpoint need to be modified to be able to set the field to return in the request (like we set the filters) 
- We do not care of processGroups (ie. services) for now , the filter is only based on process/states.
- The list of processes/states  is the list of processes/states that the user is authorize to receive 

As it is experimental , no cypress test and documentation on this iteration -> Will be done if feature is officially released

To Do : 

- [x] Modify the back to permit to set the wanted return field when searching for cards 
- [x] Add karate test 
- [x] Add in web-ui.json file an example of configuration 
- [x] Add the new screen in the UI 
- [x] Add the export featur
- [x] When user click on a line  the card is open on a popup (like actual monitoring)
- [x] Add a param to hide tags multiselect 
- [ ] Add a formatting for specific fileds  "publisher"  & "entityRecipients"  (to transform entityId to entityNames)

**Comment by vlo-rte** [comment]
After discussion, "size" field is a number of pixels. So here is an example of the field processMonitoring : 
```
"processMonitoring": [
    { "field": "startDate", "type": "date", "colName": "Start Date", "size": "200"},
    { "field": "titleTranslated", "colName": "Title", "size": "250"},
    { "field": "data.message", "colName": "My field", "size": "700"},
    { "field": "summaryTranslated", "colName": "Summary", "size": "250"},
    { "field": "data.error", "colName": "My second field", "size": "100"}
  ]
```
