### ISSUE TITLE
Add option to hide the "You have received a card hidden by...)" message

### ISSUE THREAD

**Issue by JeroenGommans** [opfab/operatorfabric-core#4736]
When you filter the cards and a new card arrives which is filtered, a red warning box is displayed with the message

`"You have received a card hidden by the filters you have activated (Timeline or card feed)"`

This can be a problem when many cards are received which are filtered. In this case, the red bar will continue to pop-up and is annoying to users.

Proposed solutions:
1. add an option to the user settings that allows a user to disable this warming
2. disable the red-bar for some time before it pop-ups again
3. add an option to the config to disable this message globally for all users

My suggestion is to implement the first solution. What do you think? Or do you think it is dangerous to allow a user to set this option?

--
Best regards,
  Jeroen

**Comment by freddidierRTE** [comment]
I would prefer the easiest solution , that is solution 3 if on you side it is ok
So for our internal use case we will keep the message as our users are supposed to read fast all message and shall not received too many at the same time. The idea is that using filtering shall be a temporary usage for searching and the user should return back to a none filtering situation 

You can implement it , be aware that it follows the new software structure , the logic shall be implemented in ui/main/src/app/business/view/core/alert/alert.view.ts and tested 

What do you think of the following name for the parameter :  "hideBusinessAlertMessages" ? (default is false)

**Comment by JeroenGommans** [comment]
The third solution is fine for us and we'll implement it in the alert.view.ts using the "hideBusinessAlertMessages".

**Comment by JeroenGommans** [comment]
@freddidierRTE 

Question: we now have three options to configure the Alerts:
- alertMessageBusinessAutoClose
- alertMessageOnBottomOfTheScreen
- hideBusinessAlertMessages

Shall I move them into their own section in the ui-config.json? E.g.
```
  "alerts": {
    "messageBusinessAutoClose": false,
    "messageOnBottomOfTheScreen": false,
    "hideBusinessMessages" : false
  } 
```

**Comment by JeroenGommans** [comment]
I have moved the configuration fields and updated the migration guide.
