### ISSUE TITLE
Archives/Logging : ExpressionChangedAfterItHasBeenCheckedError in ng serve mode (#4768)

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#4768]
Error in console when navigate to archives or logging screen in mode dev (port 4200)

![image](https://github.com/opfab/operatorfabric-core/assets/58251627/44e0a146-79a1-4a68-8ed9-bf47bc37dd42)

**Comment by HubertDuchatelle** [comment]
For the archives/Logging screen, the issue occurs when setDateFilterBounds() is called in ngAfterViewInit(), this changes the value of publishMinDate from null to an object, which causes an error because of the binding in the template line 92 [minDate]="publishMinDate".

**Comment by freddidierRTE** [comment]
Not reproduce , we use now native browser date picker so it may have sold the problem
