### ISSUE TITLE
User action logs : ExpressionChangedAfterItHasBeenCheckedError in ng serve mode

### ISSUE THREAD

**Issue by vlo-rte** [opfab/operatorfabric-core#4865]
Error in console when navigate to archives or logging screen in mode dev (port 4200) :
![image](https://github.com/opfab/operatorfabric-core/assets/57365872/68306ec9-50e8-41f9-a1b2-cd13cf86cf5c)

It also occurs when you click "reset" button. Here is the error : 
![image](https://github.com/opfab/operatorfabric-core/assets/57365872/a1794c31-1e1b-469b-a2ac-edef0cd7b5a3)

**Comment by freddidierRTE** [comment]
I do not manage to reproduce it , it may have been solved after some upgrade or refactoring
