### ISSUE TITLE
Usercard : ExpressionChangedAfterItHasBeenCheckedError in ng serve mode

### ISSUE THREAD

**Issue by vlo-rte** [opfab/operatorfabric-core#4866]
Error in console when navigate to archives or logging screen in mode dev (port 4200)
(when you go to usercard and you choose "User card examples" as service)

![image](https://github.com/opfab/operatorfabric-core/assets/57365872/f93fa50f-030d-47d4-9b32-dba513723ee1)

**Comment by freddidierRTE** [comment]
Not existing anymore (refactoring has been done on usercard)
