### ISSUE TITLE
[Thirds] Add menu entries to Third model

### ISSUE THREAD

**Issue by davidbinderRTE** [opfab/operatorfabric-core#50]
The Third Model class must be enhance with the following attribute:

-  menuEntries an array of MenuEntry.

MenuEntry is a class composed of the folowing attributes
- id : string
- url: string
- label: string (must match a i18n key declared in the i18n files)

**Comment by rlg-rte** [comment]
Commit 3933db56accf2927dcd0c8c6564a2a7ffec2c19d
