### ISSUE TITLE
Business menu: possibility to mask parameters when activating a specific menu iFrame

### ISSUE THREAD

**Issue by OlivierVoron** [opfab/operatorfabric-core#5013]
Actually, the function templateGateway.redirectToBusinessMenu gives the possibility to redirect to a specific business menu from inside a card.
The actual implementation adds the additional parameters in the main url of OperatorFabric shown in the web browser and the end-user may have the possibility to record this url as a bookmark or see the parameters provided. 
As expected and wanted, these additional parameters are also provided to the iFrame called inside OperatorFabric.

Unfortunately, if the user navigates in the application inside the iFrame, the main url of OperatorFabric will not change and it is possible that the content of this url with parameters mismatch with the real content shown by the business application in the iFrame.

**Expected behaviour:**
The proposed correction is to mask the parameters in the main url: the redirect uri will always be the same as the one that the users could select as a menu/sub-menus in the navigation bar.

**Comment by freddidierRTE** [comment]
i found a solution to do it using  history.replaceState js function but i wanted to know if this new behavior is acceptable for everybody before implementing it 
If not , I'm open to making it configurable so that it can be adjusted to meet individual needs.

**Comment by OlivierVoron** [comment]
For us, the solution seems fine

**Comment by geppyz** [comment]
I would also like to report it works fine in our setup. No problems found during testing.
