### ISSUE TITLE
As an operator, I want to access archived cards

### ISSUE THREAD

**Issue by davidbinderRTE** [opfab/operatorfabric-core#52]
Archive cards are accessible in the UI throught first level menu item to the archive page.

The Archive page is a paginated search page for the backed ArchiveCard collection.

Search query accepts the following criteria:
- time span : sets a period of activity for search. This period is defined by an optionnal start date and an optional end date. It filters in active cards. See bellow for a definition of active/inactive card.
- severity: multi value criteria. Filters in selected severity

- [ ] #33 Add archive endpoint
- [ ] #53 Add archive component

**Comment by AlexGuironnetRTE** [comment]
Implemented by OC-44
