### ISSUE TITLE
[Thirds] Add an option for menu entries: open in new tab/window

### ISSUE THREAD

**Issue by davidbinderRTE** [opfab/operatorfabric-core#54]
Part of #55 user story

Add a boolean attribute to the menu entry class to let Third Party Service define if they prefer the menu item to be openned in a new tab/windo or in an inner frame

**Comment by AlexGuironnetRTE** [comment]
As requested by end users, instead the text link opens in an iframe and an arrow icon is displayed next to it to open in a new window.
