### ISSUE TITLE
As  a Third Party Service, I need to be able to choose if menu entry links are opened in new tab/window or inner frame

### ISSUE THREAD

**Issue by davidbinderRTE** [opfab/operatorfabric-core#55]
Allow the Third Party Service to define by configuration whether its menu entries open in new tab/window or in an inner iframe.

At the time of writing, the behaviour is to open link in new tab.

- [ ] #54 Add an option for menu entrier: open in new tab/window
- [ ] #56 Handle menu entries open in new tab/window option

**Comment by AlexGuironnetRTE** [comment]
See [OC-134](https://opfab.atlassian.net/browse/OC-134)
Implemented in 0.4.1.RELEASE
