### ISSUE TITLE
Geomap pop up : option to show summary

### ISSUE THREAD

**Issue by MonaRtei** [opfab/operatorfabric-core#5784]
When the geographical map is enabled, dots/polygons are drawn on the geo-maps for all cards. When you click on dots/polygons, an infobubble shows  : "card creation date : card title".
Possible solution :
- Add an option that enables to show the card summary in the infobubble

**Comment by freddidierRTE** [comment]
Add in web-ui.json an option to define the content of the geomap popup 

The option shall be named : geomap.popupContent

Possible values : 
- cardPublishDateAndTitle
- cardSummary

Default value is publishDateAndTitle

Add in documentation
