### ISSUE TITLE
Redirection to feed from dashboard

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#5819]
When a user click on a process in the dashboard , he should be redirect on the feed with the process filter set with the process he clicks on 

When a user click on a state in the dashboard , he should be redirect on the feed with the state filter set with the states he clicks on

**Comment by quinarygio** [comment]
What if process and state filter are hidden in  feed page (hideProcessFilter and/or hideSateFilter set to true in web-ui.json ) ?

**Comment by freddidierRTE** [comment]
I suggest to activate link for process only if process filter is not hide 
and to activate link on state only if state/process filter is not hide
