### ISSUE TITLE
As a user, I want my authentication to be refreshed as per the refresh token configuration

### ISSUE THREAD

**Issue by davidbinderRTE** [opfab/operatorfabric-core#61]
The authentication must be automatically refreshed upon main token expiration when it is invalidated. We must ensure transparency of such refresh, i.e. when an access fail due to authentication we must transparently refresh the authentication and replay the access.

**Comment by AlexGuironnetRTE** [comment]
Logged in https://opfab.atlassian.net/browse/OC-349
