### ISSUE TITLE
As a User, I want to be warned when my authentication is outdated with no refresh available

### ISSUE THREAD

**Issue by davidbinderRTE** [opfab/operatorfabric-core#62]
The user must be warned and redirected to login form if he wants to. Upon re-authentication the user is still accessing the same resourec he was before its authentication timeout.

This applies both if no refresh token is available and if refresh token has expired.

**Comment by AlexGuironnetRTE** [comment]
This will be solved with the [Authentication epic](https://opfab.atlassian.net/browse/OC-415).
