### ISSUE TITLE
Get the list of tags from a custom code 

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#6239]
Currently, the list of tags for screens are defined in the web-ui.json file. This feature request proposes to load these lists from a custom code executed on demand via the Opfab API.

- A custom function shall provide the list of tags as an array of {label,value}

Example :

```
 [
    {
      "label": "Label for tag 1",
      "value": "tag1"
    },
    {
      "label": "Label for tag 2",
      "value": "tag2"
    }
  ]
```

- The function shall be defined  in a custom js on opfab loading (using what has been done in #6466)

- The function shall be registered via a new opfab API function (in ui/main/src/app/business/services/opfabAPI.service.ts) : 

```
opfab.businessconfig.registerFunctionToGetTags(method) 
```
- The function  shall take into parameter the screen name , possible list of screen names are : archives /logging/ processMonitoring

- The  function shall be asynchronous and so should return a Promise (this is due to the fact that the method can call a server to get the tags) 

- Each screen shall call this registered function via OpfabAPIService to get tags , if the function return undefined , the screen use tags defined in web-ui.json as in the actual implementation

- Register a custom function to get tag is optional so OpfabAPIService should define a default implementation returning undefined

- As an example :  modify config/docker/externalJs/example.js to register a function that return a list of tags (hardcoded in the function itself) if screenName is processMonitoring otherwise undefined 

- Add in documentation in https://opfab.github.io/documentation/current/reference_doc/#_frontend_api  in a new chapter businessConfig API

**Comment by MonaRtei** [comment]
Hi,
I tried with the value 'archives' for screen name, but it did not work. It worked with the value 'archive'.

**Comment by quinarygio** [comment]
> Hi, I tried with the value 'archives' for screen name, but it did not work. It worked with the value 'archive'.

Hi, you are right the correct screen name is "'archive', not "'archives'

**Comment by quinarygio** [comment]
> > Hi, I tried with the value 'archives' for screen name, but it did not work. It worked with the value 'archive'.
> 
> Hi, you are right the correct screen name is "'archive', not "'archives'

We have to correct the documentation
