### ISSUE TITLE
Add geographical view for monitoring process screen

### ISSUE THREAD

**Issue by freddidierRTE** [opfab/operatorfabric-core#6242]
We aim to enhance the user experience on the monitoring process screen by introducing a "View Results on a Geographical Map" feature. This feature will allow users to visualize search results on a geographical map. Here are the specifications for this feature:

- The feature should be represented as a checkbox labeled "View Results on a Geographical Map".
- Upon selection, this option should display a geographical map similar to the existing one in the feed.
- The availability of this feature should be contingent on the feed.geomap.enableMap being set to true in the web-ui.json configuration file.
- The configuration for this feature should use the settings defined under feed.geomap in the web-ui.json file.

The differences between this feature and the feed version are as follows:

- Clicking on a card on the map should open the card details in a popup.
- The map should display the results of all cards returned from the backend, instead of just the cards currently in memory.
- The map should not update in real-time; it should only update when the user clicks on the search button.

Please note that no Cypress tests are required for this feature. 

The feature should be documented in the Process Monitoring section of the OperatorFabric documentation (https://opfab.github.io/documentation/current/reference_doc/#_process_monitoring).

**Comment by MonaRtei** [comment]
Thanks for the new feature, it works like a charm.
