### ISSUE TITLE
Add filters LESS_THAN & GREATER_THAN to org.opfab.cards.model.FilterMatchTypeEnum class

### ISSUE THREAD

**Issue by bengoutaeli** [opfab/operatorfabric-core#6319]
In the case of a search for cards whose **publishDate** is less than a specific date for example. Would it be possible to add the `LESS_THAN` & `GREATER_THAN` filters in order to be comparable ?

**Comment by freddidierRTE** [comment]
Ok this would be named : LESSTHAN GREATERTHAN 

Add Karate test in src/test/api/karate/cards/fetchArchivedCardsWithFilter.feature
