### ISSUE TITLE
Give the possibility to update an existing card by modifying only some properties

### ISSUE THREAD

**Issue by bengoutaeli** [opfab/operatorfabric-core#6456]
1. And to take into account the both CardActionEnum during the updating :
 1.1. `KEEP_EXISTING_PUBLISH_DATE`,
 1.2. `KEEP_EXISTING_ACKS_AND_READS`
2. Allow to choose the properties to be modified

**Comment by freddidierRTE** [comment]
To do that : 

- [x] - Implement an http PATCH method to the end point for sending card
- [x] - It shall not be possible to modify processInstanceId and process
- [x] - Add karate test 
- [x] - Add in documentation new chapter in https://opfab.github.io/documentation/current/reference_doc/#_sending_cards  named "patch a card"
