### ISSUE TITLE
Link the period selection for the Dashboard, Card Feed and Monitoring screens

### ISSUE THREAD

**Issue by SaschaEschmann** [opfab/operatorfabric-core#6463]
Hello OperatorFabric's colleagues,

We noticed that currently, the period selection of the different screens having the timeline (Dashboard, Card Feed and Monitoring) is not linked.

We expected that this period selection is the same for the 3 screens so once I change the period in one screen I keep it by navigating to the other(s) screen(s).

I remain available to discuss it further.

Kind regards,

**Comment by freddidierRTE** [comment]
Solving means :
 

- When loading opfab , we keep the actual behaviour , we get in the storage the domain (Year,Month, ...) and base on the domain we set the chosen period containing the current date.

 
- When navigating in opfab between feed / monitoring and dashboard we keep the period (startDate - endDate) in memory and not only the domain as it is today 



To do that , we need to proceed to a refactoring :

Idea is to define a service which manage the realtime current domain , let's call it RealtimeDomain

The role of this service would be to keep in memory :
- the domain name : Y,M,7D,W,TR
- the start and end date 
- the lock/unlock status 


It would have method to compute domain start and end date , in fact these methods are already existing in timeline-buttons.components 

This service shall as well manage the preference 'opfab.timeLine.domain' as already done in timeline-buttons.components 

And finally , it is  the service that is in charge of modifying the business date filter (`this.filteredLightCardStore.updateFilter()`)

When timeline-button.components init,  it would set the domain and the associated date via the service 

In calendar component you need to reset the domain when in calendar (in datesRangeChange method)
