### ISSUE TITLE
Allowing to load a custom handlebars helper file

### ISSUE THREAD

**Issue by bengoutaeli** [opfab/operatorfabric-core#6531]
In the same idea as https://github.com/opfab/operatorfabric-core/pull/6517/files#. Allow to load a custom handlebars helper file Independent of base one

**Comment by freddidierRTE** [comment]
**Feature :** 

Add a new method in Frontend API (https://opfab.github.io/documentation/current/reference_doc/#_frontend_api)

Method is opfab.handlebars.registerCustomHelper

This method should register a new Helper function . The objective is to call this method on startup via custom js


**Implementation :** 

Declare the method in ui/main/src/app/business/services/opfabAPI.service.ts in initAPI() 



**Testing**  

Replace the actual config/docker/externalJs/example.js by a new file handlebarsExample.js 

In this file add an example helper to convert an opfab severity to his corresponding color

Use this helper in src/test/resources/bundles/cypress/template/kitchenSink.handlebars and check the resutl in cypress test "Check card detail" in src/test/cypress/cypress/integration/CardDetail.spec.js

**Documentation** 

Add in documentation https://opfab.github.io/documentation/archives/4.4.0-RC.RELEASE/docs/single_page_doc.html#_frontend_api

TO BE REVIEWED BY freddidierRTE
