### ISSUE TITLE
Usercard: when sending "Confirmation" user card a sound notification is played while it should not

### ISSUE THREAD

**Issue by quinarygio** [opfab/operatorfabric-core#6532]
To reproduce:
 Activate sound for "ACTION" severity in user settings.
Send a new Usercard examples- Confirmation usercard.
A sound notification is played because when sending Confirmation usercard, a child response card is also sent automatically.  The child card triggers an update of the parent card (to set hasChildCardFromCurrentUserEntity = true) on lightCardsStore, so the sound notification service receives the parent card twice. the first time the sound is not played because card id equals lastSentCardId, the second time instead the sound is played.

**Comment by freddidierRTE** [comment]
A solution could be to always keep lastCardSentId in memory with the time lastCardSendId was set.
So to be sure it is not a card update that needs to be sounded (like a remind)  check publish date is close to the time lastCardSendId was set.

However, this solution does not solve all problems 

Example : the user send two cards and do not read them (i.e click on card on the feed) , if a user of the same entity respond to the first card , the lightcard will be update in memory and trigger a sound as it is not the last send card (and the card is not read by current user)

So a more global approach should be to store an array of last sent cards ( id + card sending date ) having a mechanism of cleaning the array after a while based an card sending date 


This rules to define if card is to be sounded  can be a little tricky , the proposal is to solve the problem externalizing the decision of sound in specific class with unit test 

Let 's say a class named SoundDecision.ts with a method isCardToBeSounded

The result shall integrated all the rules using severity , dates , read status , lastCardSend ..
