### ISSUE TITLE
As an Operator, I want to be notified of important incoming cards

### ISSUE THREAD

**Issue by davidbinderRTE** [opfab/operatorfabric-core#68]
When a card enters the client throught SSE, if the card is important the operator needs to be visually notified.

The definition of important may vary from usage and may need to be configurable.

A first implementation of "important" may be cards with ALARM severity.

The notion of important must be decoupled from start to allow for ease of evolution. 

- [ ] #67 Include toaster generic message display

**Comment by AlexGuironnetRTE** [comment]
No one has asked for this yet.
