### ISSUE TITLE
Use HTML in tooltip component

### ISSUE THREAD

**Issue by bengoutaeli** [opfab/operatorfabric-core#6826]
According to old issue [Add a tooltip component for template or external apps #4518](https://github.com/opfab/operatorfabric-core/issues/4518).

We want to use HTML (using of _Handlebars_ of course) in order to have specific content within tooltip in order to apply it in this example 
![image](https://github.com/user-attachments/assets/64bdbec1-0dcb-491f-9e53-fa8f253c22a9)

**The deadline for this feature is early to mid-September.**

**Comment by freddidierRTE** [comment]
I check , the actual tooltip permit only a line of text

We need to change it to have HTML inside

https://www.w3schools.com/howto/howto_css_tooltip.asp

**Comment by bengoutaeli** [comment]
Is it possible to check the `opfab-tooltip` within an `opfab-table td` ? (as the screen example) @freddidierRTE

**Comment by freddidierRTE** [comment]
> Is it possible to check the `opfab-tooltip` within an `opfab-table td` ? (as the screen example) [@freddidierRTE](https://github.com/freddidierRTE)

yes it is possible to have the actual tooltip in a td .

the new tootip with HTML should as well be available in a td 



Working example : 

```
            <p>TABLE</p>
            <div class="opfab-table">
                <table>
                    <thead>
                        <tr>
                            <th>Header 1</th>
                            <th>Header 2</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td> <span  opfab-tooltip-text="Message " class="opfab-tooltip"> Row 1 Column 1  </span> </td>
                            <td> <span  opfab-tooltip-text="Message " class="opfab-tooltip"> Row 1 Column 2  </span> </td>
                        </tr>
                        <tr>
                            <td> <span  opfab-tooltip-text="Message " class="opfab-tooltip"> Row 2 Column 1  </span> </td>
                            <td> <span  opfab-tooltip-text="Message " class="opfab-tooltip"> Row 2 Column 2  </span> </td>
                        </tr>
                    </tbody>
                </table>
            </div>
```
