### ISSUE TITLE
Processus monitoring example: do not use richMessage field as custom column

### ISSUE THREAD

**Issue by quinarygio** [opfab/operatorfabric-core#6861]
"processMonitoring": {
    "fields": [
      { "field": "startDate", "type": "date", "colName": "Start Date", "size": "200"},
      { "field": "titleTranslated", "colName": "Title", "size": "250"},
      { "field": "entityRecipients", "type": "array", "colName": "Entity Recipients", "size": "400"},
      { "field": "data.richMessage", "colName": "My field", "size": "300"},
      { "field": "summaryTranslated", "colName": "Summary", "size": "250"},
      { "field": "data.error", "colName": "My second field", "size": "100"}
    ],

**Comment by freddidierRTE** [comment]
Show instead data.stateName instead
