### ISSUE TITLE
Update documentation for settting/getting log level using provided scripts

### ISSUE THREAD

**Issue by quinarygio** [opfab/operatorfabric-core#6949]
Documentation is not updated for usage of scripts in src/test/resources/logs:
getLogsNodeService.sh
getLogs.sh
setLogsNodeService.sh
setLogs.sh

The password parameter is not documented

Es: 
./setLogs.sh 

Usage : setLogs.sh host:port level user password opfab_url

While in documentation:

To set the log level for ROOT logger of a service it is possible to call the provided script  
https://github.com/opfab/operatorfabric-core/tree/master/src/test/resources/logs/setLogs.sh[src/test/resources/logs/setLogs.sh] as follows: `setLogs.sh <server:port> <log_level>  <user> <opfab_url>`. For example to set the log level to DEBUG for "card-publication" service  execute: `setLogs.sh localhost:2102 DEBUG admin http://localhost`

**Comment by freddidierRTE** [comment]
These scripts are not needed anymore and will be removed:  https://github.com/opfab/operatorfabric-core/issues/7126
