### ISSUE TITLE
Use the native Opfab popup message

### ISSUE THREAD

**Issue by bengoutaeli** [opfab/operatorfabric-core#7017]
Is it possible to show through an opfab generic method the native opfab popup message and to configure it like the call of opfab.currentCard.registerFunctionToGetUserResponse for example ?
![image](https://github.com/user-attachments/assets/ddbda105-2315-4627-a056-a151c79b3c4d)

**Comment by freddidierRTE** [comment]
**FEATURE**

So we can add a new method opfab.alertMessage.show("My message", messageLevel)

messagLevel has four possible values : 
- opfab.alertMessage.messageLevel.ERROR
- opfab.alertMessage.messageLevel.INFO
-  opfab.alertMessage.messageLevel.DEBUG
-  opfab.alertMessage.messageLevel.BUSINESS

**IMPLEMENTATION**

Implementation of opfab.alertMessage.messageLevel for example :  

```
const opfab.alertMessage.messageLevel = Object.freeze({
    ERROR: 0,
    INFO: 1,
    DEBUG: 2,
    BUSINESS: 3
});
```

Test it in cypress test using kitchenSink template
Add in documentation
