### ISSUE TITLE
Documentation / Guide on How To Contribute to the project?

### ISSUE THREAD

**Issue by joesan** [opfab/operatorfabric-core#71]
Is there any documentation on Getting Started guide for developers who wish to contribute to the project?

**Comment by AlexGuironnetRTE** [comment]
Hello,

Thank you for your interest! There is no getting started guide yet but we are working on it and will share it as soon as possible. Would you like to get in touch to discuss your interest in the project ?

**Comment by joesan** [comment]
Sure! How do we get in touch? Do you have a Skype user? Is there a Slack channel for the project?

**Comment by joesan** [comment]
I work for a utility company and I have good experience with the Flexibility market and I would like to join the Linux Energy Foundation project. So please let me know how I can contribute and what the goals of the projects are?

**Comment by AlexGuironnetRTE** [comment]
Hi !
Sorry for the delay, we wanted to have a few things to show you before getting back to you.
As you can see:

- We've added a CONTRIBUTING (even though there is still a lot left to be defined)
- We followed your recommendation and created a Mattermost channel (it's very similar to Slack), please [join it](https://team.opfab.org/signup_user_complete/?id=7nhtz5psobgpud6yqzrbibmdtw)!

We're currently focusing on the documentation (reference, javadoc and getting started guides) and pushing this content to the website (https://opfab.github.io/) as we write it, so feel free to take a look and let us now what you think, any feedback will be greatly appreciated!
