### ISSUE TITLE
Compliance with MongoDB 7

### ISSUE THREAD

**Issue by SaschaEschmann** [opfab/operatorfabric-core#7229]
Hi OpFab colleagues,

Would it be possible to check the compliance of OperatorFabric with the version 7 of MongoDB ? As a matter of fact, this has been requested by our customer for one of our projects using OperatorFabric.

Thanks in advance.

Kind regards,

**Comment by ClementBouvierN** [comment]
Hello,

We recently upgraded MongoDB from 5 to 6 and then from 6 to 7 and no issue arose. We confirm we're compatible with version 7 of MongoDB.

Kind regards

**Comment by SaschaEschmann** [comment]
Hello @ClementBouvierN ,

Alright, thanks a lot for the support.

Have a nice day.
