### ISSUE TITLE
Number of entities in the header of a "smart" notification

### ISSUE THREAD

**Issue by SaschaEschmann** [opfab/operatorfabric-core#7230]
Hi OpFab colleagues,

We noticed that currently in the header of the smart notifications (notifications in which you can provide an answer), the number of displayed entity is limited to 3 and the others are in "..." via a clickable tool-tip:

![image](https://github.com/user-attachments/assets/484e3221-c78a-450f-bccf-171a979b7238)

Would it be possible to extend this number of displayed entity ? 6 would be sufficient for our use-case.

Thanks in advance.

Kind regards,

**Comment by freddidierRTE** [comment]
The idea is to adopt the same solution as for https://github.com/opfab/operatorfabric-core/issues/6729

**Comment by SaschaEschmann** [comment]
Thanks a lot for the addition of this enhancement !
