### ISSUE TITLE
Edit card link : add it as a button

### ISSUE THREAD

**Issue by MonaRtei** [opfab/operatorfabric-core#7525]
In a card created from a user card, we need to add a link to edit the card. Currently, the user can edit the card by clicking on the pencil (EDIT) icon. Here, the recipient who needs to edit the card is not the publisher. We think it would be more user-friendly to have the possiblity to add a button within the card to edit the card.

![image](https://github.com/user-attachments/assets/a1718c56-4fb4-4449-9ba2-5460bab6328f)

Thanks.

**Comment by freddidierRTE** [comment]
To do that : 

Add two methods in opfab API : 
-  opfab.currentCard.isUserAllowedToEdit()
-  opfab.currentCard.editCard()

Use it in message example : 

![image](https://github.com/user-attachments/assets/013026b8-73b3-42ef-a73d-107fc06db4f8)

Add a cypress test
