### ISSUE TITLE
 Error with startDate and endDate when parent card is modified and published by external recipient

### ISSUE THREAD

**Issue by MonaRtei** [opfab/operatorfabric-core#7709]
This error had never occurred before because it only happens when the parent card is sent directly to an external-recipient. Previously, for withdrawals:

1. We received the child card.
2. From the child card, we retrieved the parent card using the cards-consultation API.
3. Finally, we modified and republished it via the cards-publication API.

However, it seems that when using the cards-consultation API, the dates are retrieved correctly. In contrast, when a parent card is sent directly to an external-recipient, the retrieved dates are divided by 1000.

Date attribut in card received from API cards-consultation
![card-consultation-api_card-received](https://github.com/user-attachments/assets/31bb6dfb-b656-4a28-b630-5866e63c7f6c)

Date attribut in card received as an external-recipient
![external-recipient_card-received](https://github.com/user-attachments/assets/abf219b4-9859-4feb-9c35-a789c870ac4e)

**Comment by freddidierRTE** [comment]
Solved by https://github.com/opfab/operatorfabric-core/issues/7680
