### ISSUE TITLE
JSON not valid in Get Started documentation

### ISSUE THREAD

**Issue by vincentbarbesant** [opfab/operatorfabric-core#88]
In the ["Getting started" documentation of release 0.3.1](https://opfab.github.io/documentation/0.3.1.RELEASE/start/#_card_creation_and_sending), the JSON example in chapter 5.2.1 is not valid, some commas are missing.

It makes the POST request of 5.2.2 fail.

**Comment by jeandemanged** [comment]
I proposed a fix in pull request #89

**Comment by AlexGuironnetRTE** [comment]
Fixed by pull request #89. Thanks!
