### ISSUE TITLE
Docker-compose file points to wrong image location.

### ISSUE THREAD

**Issue by Laurentjg** [opfab/operatorfabric-core#94]
In operatorfabric-core/src/main/docker/docker-compose.yml there are links to two images for the same service: operatorfabric.thirds:

image: "org.lfenergy.operatorfabric/config" and later on to 
image: "org.lfenergy.operatorfabric/thirds".

The following error-message appears after docker-compose up:
ERROR: Get https://org.lfenergy.operatorfabric/v2/: dial tcp: lookup org.lfenergy.operatorfabric on 194.109.6.66:53: no such host

The message also appears if the fist operatorfabric.thirds declaration from the yml file is deleted.
I can reach port 53 on this server with nmap, but only including the -Pn option.
How to get it running with the right images?

**Comment by francoisjolain** [comment]
Hi,
You can use operatorfabric-core/src/main/docker/**deploy**/docker-compose.yml to deploy operator fabric by docker-compose.

We will clean all docker-compose.yml file to avoid such misunderstand.

**Comment by HanaeSafiRTE** [comment]
Hi Laurent 
Is everything going well?
We remain at your disposal for further information :)

**Comment by Laurentjg** [comment]
Hi @HanaeSafiRTE ,
[9f094b7db914log.log](https://github.com/opfab/operatorfabric-core/files/3582686/9f094b7db914log.log)
Actually the "deploy" docker is not working either. It starts up all containers. After a while the keycloack stops, followed by the of-users-business-services and seconds after that much more will stop. The only containers still alive are:
- web-ui
- registry-cloud-service
- rabbitmq
- mongodb

I logged (docker logs [id] > [file])  the users-business-services that stoped as one of the first onces. A developer supported me to find some possible causes in it. It seems that there is a problem with a configuration file at the client for accessing the mongodb.

Caused by: java.lang.NullPointerException: null
                at org.lfenergy.operatorfabric.springtools.configuration.mongo.MongoConfiguration.mongoSettings(MongoConfiguration.java:138) ~[spring-mongo-utilities-0.8.1.SNAPSHOT.jar!/:na]

I just want to spin the docker-compose up to interact with operator fabric and make a mock-up demo system. As I'm not a java developer I unfortunately cannot look deeper into the problem.
For more details I attached the logfile. If there is an easy way to get _Of_ running in one or two hours, please let me know. Do you like me to make a new Issue of it?

**Comment by HanaeSafiRTE** [comment]
Hi Laurent,
Thanks for your answer

**Comment by HanaeSafiRTE** [comment]
Hi Laurent,

Thank you for your answer. Could you please open a new issue?
We will work on it soon.
best regards
